// Code generated by fullpipe. DO NOT EDIT.

package bybit

import "context"

type BybitApi interface {
	// Get Announcement
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/announcement
	GetAnnouncementsIndex(context.Context, AnnouncementsIndexQuery) (AnnouncementsIndex, error)

	// Demo Trading Service
	//
	// **Mainnet Demo Trading URL:**
	// Rest API: `https://api-demo.bybit.com`
	// Websocket: `wss://stream-demo.bybit.com` (note that this only supports the private streams; public data is identical to that found on mainnet with `wss://stream.bybit.com`; WS Trade is not supported)
	//
	// Bybit v5 Open API supports demo trading account, but please note **not** every API is available for demo trading account because demo trading service is mainly for trading experience purpose, so that it does not have a complete function compared with the real trading service.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/demo
	AccountDemoApplyMoney(context.Context, AccountDemoApplyMoneyParams) (AccountDemoApplyMoneyResult, error)

	// Get System Status
	//
	// Get the system status when there is a platform maintenance or service incident.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/system-status
	GetSystemStatus(context.Context, SystemStatusQuery) (SystemStatus, error)

	// Get Bybit Server Time
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/time
	GetMarketTime(context.Context) (MarketTime, error)

	// Get Kline
	//
	// Query for historical klines (also known as candles/candlesticks). Charts are returned in groups based on the requested interval.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/kline
	GetMarketKline(context.Context, MarketKlineQuery) (MarketKline, error)

	// Get Mark Price Kline
	//
	// Query for historical [mark price](https://www.bybit.com/en-US/help-center/s/article/Glossary-Bybit-Trading-Terms) klines. Charts are returned in groups based on the requested interval.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/mark-kline
	GetMarketMarkPriceKline(context.Context, MarketMarkPriceKlineQuery) (MarketMarkPriceKline, error)

	// Get Index Price Kline
	//
	// Query for historical [index price](https://www.bybit.com/en-US/help-center/s/article/Glossary-Bybit-Trading-Terms) klines. Charts are returned in groups based on the requested interval.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/index-kline
	GetMarketIndexPriceKline(context.Context, MarketIndexPriceKlineQuery) (MarketIndexPriceKline, error)

	// Get Premium Index Price Kline
	//
	// Query for historical [premium index](https://www.bybit.com/data/basic/linear/index-price/premium-index?symbol=BTCUSDT) klines. Charts are returned in groups based on the requested interval.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/premium-index-kline
	GetMarketPremiumIndexPriceKline(context.Context, MarketPremiumIndexPriceKlineQuery) (MarketPremiumIndexPriceKline, error)

	// Get Instruments Info
	//
	// Query for the instrument specification of online trading pairs.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/instrument
	GetMarketInstrumentsInfo(context.Context, MarketInstrumentsInfoQuery) error

	// Get Orderbook
	//
	// Query for orderbook depth data.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/orderbook
	GetMarketOrderbook(context.Context, MarketOrderbookQuery) (MarketOrderbook, error)

	// Get RPI Orderbook
	//
	// Query for orderbook depth data.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/rpi-orderbook
	GetMarketRpiOrderbook(context.Context, MarketRpiOrderbookQuery) (MarketRpiOrderbook, error)

	// Get Tickers
	//
	// Query for the latest price snapshot, best bid/ask price, and trading volume in the last 24 hours.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/tickers
	GetMarketTickers(context.Context, MarketTickersQuery) error

	// Get Funding Rate History
	//
	// To query the funding rate interval, please refer to the [instruments-info](/docs/v5/market/instrument) endpoint.
	//
	// Query for historical funding rates. Each symbol has a different funding interval. For example, if the interval is 8 hours and the current time is UTC 12, then it returns the last funding rate, which settled at UTC 8.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/history-fund-rate
	GetMarketFundingHistory(context.Context, MarketFundingHistoryQuery) (MarketFundingHistory, error)

	// Get Recent Public Trades
	//
	// You can download archived historical trades from the [website](https://www.bybit.com/derivatives/en/history-data)
	//
	// Query recent public trading history in Bybit.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/recent-trade
	GetMarketRecentTrade(context.Context, MarketRecentTradeQuery) (MarketRecentTrade, error)

	// Get Open Interest
	//
	// Get the [open interest](https://www.bybit.com/en-US/help-center/s/article/Glossary-Bybit-Trading-Terms) of each symbol.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/open-interest
	GetMarketOpenInterest(context.Context, MarketOpenInterestQuery) (MarketOpenInterest, error)

	// Get Historical Volatility
	//
	// Query option historical volatility
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/iv
	GetMarketHistoricalVolatility(context.Context, MarketHistoricalVolatilityQuery) (MarketHistoricalVolatility, error)

	// Get Insurance Pool
	//
	// Query for Bybit [insurance pool](https://www.bybit.com/en/announcement-info/insurance-fund/) data (BTC/USDT/USDC etc)
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/insurance
	GetMarketInsurance(context.Context, MarketInsuranceQuery) (MarketInsurance, error)

	// Get Risk Limit
	//
	// Query for the [risk limit](https://www.bybit.com/en/help-center/article/Risk-Limit-Perpetual-and-Futures) margin parameters. This information is also displayed on the website [here](https://www.bybit.com/en/announcement-info/margin-parameters/).
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/risk-limit
	GetMarketRiskLimit(context.Context, MarketRiskLimitQuery) (MarketRiskLimit, error)

	// Get Delivery Price
	//
	// Get the delivery price.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/delivery-price
	GetMarketDeliveryPrice(context.Context, MarketDeliveryPriceQuery) (MarketDeliveryPrice, error)

	// Get New Delivery Price
	//
	// Get historical option delivery prices.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/new-delivery-price
	GetMarketNewDeliveryPrice(context.Context, MarketNewDeliveryPriceQuery) (MarketNewDeliveryPrice, error)

	// Get Long Short Ratio
	//
	// This refers to the net long and short positions as percentages of all position holders during the selected time.
	// Long account ratio = Number of holders with long positions / Total number of holders
	// Short account ratio = Number of holders with short positions / Total number of holders
	// Long-short account ratio = Long account ratio / Short account ratio
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/long-short-ratio
	GetMarketAccountRatio(context.Context, MarketAccountRatioQuery) (MarketAccountRatio, error)

	// Get Index Price Components
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/index-components
	GetMarketIndexPriceComponents(context.Context, MarketIndexPriceComponentsQuery) (MarketIndexPriceComponents, error)

	// Get Order Price Limit
	//
	// For derivative trading order price limit, refer to [announcement](https://announcements.bybit.com/en/article/adjustments-to-bybit-s-derivative-trading-limit-order-mechanism-blt469228de1902fff6/)
	// For spot trading order price limit, refer to [announcement](https://announcements.bybit.com/en/article/title-adjustments-to-bybit-s-spot-trading-limit-order-mechanism-blt786c0c5abf865983/)
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/order-price-limit
	GetMarketPriceLimit(context.Context, MarketPriceLimitQuery) (MarketPriceLimit, error)

	// Get ADL Alert
	//
	// Subscribe to the [ADL WebSocket topic](/docs/v5/websocket/public/adl-alert) for faster updates.
	//
	// Query for [ADL](https://www.bybit.com/en/help-center/article/Auto-Deleveraging-ADL) (auto-deleveraging mechanism) alerts and insurance pool information.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/adl-alert
	GetMarketAdlAlert(context.Context, MarketAdlAlertQuery) (MarketAdlAlert, error)

	// Get Fee Group Structure
	//
	// For more details please refer to the [fee structure update announcement](https://announcements.bybit.com/article/bybit-fee-structure-update-for-pro-and-market-maker-clients-blt06875b6d623e7581/).
	//
	// Query for the [group fee structure](https://www.bybit.com/en/help-center/article/Group-Fee-Structure-Symbol-Grouping) and fee rates.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/market/fee-group-info
	GetMarketFeeGroupInfo(context.Context, MarketFeeGroupInfoQuery) (MarketFeeGroupInfo, error)

	// Place Order
	//
	// This endpoint supports to create the order for Spot, Margin trading, USDT perpetual, USDT futures, USDC perpetual, USDC futures, Inverse Futures and Options.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/create-order
	OrderCreate(context.Context, OrderCreateParams) (OrderCreateResult, error)

	// Amend Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/amend-order
	OrderAmend(context.Context, OrderAmendParams) (OrderAmendResult, error)

	// Cancel Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/cancel-order
	OrderCancel(context.Context, OrderCancelParams) (OrderCancelResult, error)

	// Get Open & Closed Orders
	//
	// Primarily query unfilled or partially filled orders in **real-time**, but also supports querying recent 500 closed status (Cancelled, Filled) orders. Please see the usage of request param `openOnly`.
	// And to query older order records, please use the [order history](/docs/v5/order/order-list) interface.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/open-order
	GetOrderRealtime(context.Context, OrderRealtimeQuery) (OrderRealtime, error)

	// Cancel All Orders
	//
	// Cancel all open orders
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/cancel-all
	OrderCancelAll(context.Context, OrderCancelAllParams) (OrderCancelAllResult, error)

	// Get Order History
	//
	// Query order history. As order creation/cancellation is **asynchronous**, the data returned from this endpoint may delay. If you want to get real-time order information, you could query this [endpoint](/docs/v5/order/open-order) or rely on the [websocket stream](/docs/v5/websocket/private/order) (recommended).
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/order-list
	GetOrderHistory(context.Context, OrderHistoryQuery) (OrderHistory, error)

	// Get Trade History
	//
	// Query users' execution records, sorted by `execTime` in descending order.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/execution
	GetExecutionList(context.Context, ExecutionListQuery) (ExecutionList, error)

	// Batch Place Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/batch-place
	OrderCreateBatch(context.Context, OrderCreateBatchParams) (OrderCreateBatchResult, error)

	// Batch Amend Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/batch-amend
	OrderAmendBatch(context.Context, OrderAmendBatchParams) (OrderAmendBatchResult, error)

	// Batch Cancel Order
	//
	// This endpoint allows you to cancel more than one open order in a single request.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/batch-cancel
	OrderCancelBatch(context.Context, OrderCancelBatchParams) (OrderCancelBatchResult, error)

	// Get Borrow Quota (Spot)
	//
	// Query the available balance for Spot trading and Margin trading
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/spot-borrow-quota
	GetOrderSpotBorrowCheck(context.Context, OrderSpotBorrowCheckQuery) (OrderSpotBorrowCheck, error)

	// Set Disconnect Cancel All
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/dcp
	OrderDisconnectedCancelAll(context.Context, OrderDisconnectedCancelAllParams) error

	// Pre Check Order
	//
	// This endpoint is used to calculate the changes in IMR and MMR of UTA account before and after placing an order.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/order/pre-check-order
	OrderPreCheck(context.Context) (OrderPreCheckResult, error)

	// Get Position Info
	//
	// Query real-time position data, such as position size, cumulative realized PNL, etc.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position
	GetPositionList(context.Context, PositionListQuery) (PositionList, error)

	// Set Leverage
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/leverage
	PositionSetLeverage(context.Context, PositionSetLeverageParams) error

	// Switch Position Mode
	//
	// It supports to switch the position mode for **USDT perpetual** and **Inverse futures**. If you are in one-way Mode, you can only open one position on Buy or Sell side. If you are in hedge mode, you can open both Buy and Sell side positions simultaneously.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/position-mode
	PositionSwitchMode(context.Context, PositionSwitchModeParams) error

	// Set Trading Stop
	//
	// Set the take profit, stop loss or trailing stop for the position.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/trading-stop
	PositionTradingStop(context.Context, PositionTradingStopParams) error

	// Set Auto Add Margin
	//
	// Turn on/off auto-add-margin for **isolated** margin position
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/auto-add-margin
	PositionSetAutoAddMargin(context.Context, PositionSetAutoAddMarginParams) error

	// Add Or Reduce Margin
	//
	// Manually add or reduce margin for **isolated** margin position
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/manual-add-margin
	PositionAddMargin(context.Context, PositionAddMarginParams) (PositionAddMarginResult, error)

	// Get Closed PnL
	//
	// Query user's closed profit and loss records
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/close-pnl
	GetPositionClosedPnl(context.Context, PositionClosedPnlQuery) (PositionClosedPnl, error)

	// Get Closed Options Positions
	//
	// Query user's closed options positions, sorted by `closeTime` in descending order.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/close-position
	GetPositionGetClosedPositions(context.Context, PositionGetClosedPositionsQuery) (PositionGetClosedPositions, error)

	// Move Position
	//
	// You can move positions between sub-master, master-sub, or sub-sub UIDs when necessary
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/move-position
	PositionMovePositions(context.Context, PositionMovePositionsParams) (PositionMovePositionsResult, error)

	// Get Move Position History
	//
	// You can query moved position data by master UID api key
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/move-position-history
	GetPositionMoveHistory(context.Context, PositionMoveHistoryQuery) (PositionMoveHistory, error)

	// Confirm New Risk Limit
	//
	// It is only applicable when the user is marked as only reducing positions (please see the isReduceOnly field in the [Get Position Info](/docs/v5/position) interface). After the user actively adjusts the risk level, this interface is called to try to calculate the adjusted risk level, and if it passes (retCode=0), the system will remove the position reduceOnly mark. You are recommended to call [Get Position Info](/docs/v5/position) to check `isReduceOnly` field.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/position/confirm-mmr
	PositionConfirmPendingMmr(context.Context, PositionConfirmPendingMmrParams) error

	// Get Pre-upgrade Order History
	//
	// By category="linear", you can query USDT Perps, USDC Perps data occurred during classic account
	// By category="spot", you can query Spot data occurred during classic account
	// By category="option", you can query Options data occurred during classic account
	// By category="inverse", you can query Inverse Contract data occurred during **classic account or [UTA1.0](/docs/v5/acct-mode#uta-10)**
	//
	// After the account is upgraded to a Unified account, you can get the orders which occurred before the upgrade.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/pre-upgrade/order-list
	GetPreUpgradeOrderHistory(context.Context, PreUpgradeOrderHistoryQuery) (PreUpgradeOrderHistory, error)

	// Get Pre-upgrade Trade History
	//
	// By category="linear", you can query USDT Perps, USDC Perps data occurred during classic account
	// By category="spot", you can query Spot data occurred during classic account
	// By category="option", you can query Options data occurred during classic account
	// By category="inverse", you can query Inverse Contract data occurred during **classic account or [UTA1.0](/docs/v5/acct-mode#uta-10)**
	//
	// Get users' execution records which occurred before you upgraded the account to a Unified account, sorted by `execTime` in descending order It supports to query USDT perpetual, USDC perpetual, Inverse perpetual, Inverse futures, Spot and Option.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/pre-upgrade/execution
	GetPreUpgradeExecutionList(context.Context, PreUpgradeExecutionListQuery) (PreUpgradeExecutionList, error)

	// Get Pre-upgrade Closed PnL
	//
	// Query user's closed profit and loss records from before you upgraded the account to a Unified account. The results are sorted by `updatedTime` in descending order. it only supports to query USDT perpetual, Inverse perpetual and Inverse Futures.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/pre-upgrade/close-pnl
	GetPreUpgradePositionClosedPnl(context.Context, PreUpgradePositionClosedPnlQuery) (PreUpgradePositionClosedPnl, error)

	// Get Pre-upgrade Transaction Log
	//
	// You can get USDC Perpetual, Option records.
	//
	// By category="linear", you can query USDC Perps transaction logs occurred during classic account By category="option", you can query Options transaction logs occurred during classic account
	//
	// Query transaction logs which occurred in the USDC Derivatives wallet before the account was upgraded to a Unified account.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/pre-upgrade/transaction-log
	GetPreUpgradeAccountTransactionLog(context.Context, PreUpgradeAccountTransactionLogQuery) (PreUpgradeAccountTransactionLog, error)

	// Get Pre-upgrade Delivery Record
	//
	// Query delivery records of Options before you upgraded the account to a Unified account, sorted by `deliveryTime` in descending order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/pre-upgrade/delivery
	GetPreUpgradeAssetDeliveryRecord(context.Context, PreUpgradeAssetDeliveryRecordQuery) (PreUpgradeAssetDeliveryRecord, error)

	// Get Pre-upgrade USDC Session Settlement
	//
	// Query session settlement records of USDC perpetual before you upgrade the account to Unified account.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/pre-upgrade/settlement
	GetPreUpgradeAssetSettlementRecord(context.Context, PreUpgradeAssetSettlementRecordQuery) (PreUpgradeAssetSettlementRecord, error)

	// Get Wallet Balance
	//
	// Obtain wallet balance, query asset information of each currency. By default, currency information with assets or liabilities of 0 is not returned.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/wallet-balance
	GetAccountWalletBalance(context.Context, AccountWalletBalanceQuery) (AccountWalletBalance, error)

	// Get Transferable Amount (Unified)
	//
	// Query the available amount to transfer of a specific coin in the Unified wallet.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/unified-trans-amnt
	GetAccountWithdrawal(context.Context, AccountWithdrawalQuery) (AccountWithdrawal, error)

	// Get Transaction Log
	//
	// Query for transaction logs in your Unified account. It supports up to 2 years worth of data.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/transaction-log
	GetAccountTransactionLog(context.Context, AccountTransactionLogQuery) (AccountTransactionLog, error)

	// Get Account Info
	//
	// Query the account information, like margin mode, account mode, etc.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/account-info
	GetAccountInfo(context.Context) (AccountInfo, error)

	// Get Account Instruments Info
	//
	// Query for the instrument specification of online trading pairs that available to users.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/instrument
	GetAccountInstrumentsInfo(context.Context, AccountInstrumentsInfoQuery) error

	// Manual Borrow
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/borrow
	AccountBorrow(context.Context, AccountBorrowParams) (AccountBorrowResult, error)

	// Manual Repay Without Asset Conversion
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/no-convert-repay
	AccountNoConvertRepay(context.Context, AccountNoConvertRepayParams) (AccountNoConvertRepayResult, error)

	// Manual Repay
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/repay
	AccountRepay(context.Context, AccountRepayParams) (AccountRepayResult, error)

	// Get Fee Rate
	//
	// Get the trading fee rate.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/fee-rate
	GetAccountFeeRate(context.Context, AccountFeeRateQuery) (AccountFeeRate, error)

	// Get Collateral Info
	//
	// Get the collateral information of the current unified margin account, including loan interest rate, loanable amount, collateral conversion rate, whether it can be mortgaged as margin, etc.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/collateral-info
	GetAccountCollateralInfo(context.Context, AccountCollateralInfoQuery) (AccountCollateralInfo, error)

	// Get DCP Info
	//
	// Query the DCP configuration of the account. Before calling the interface, please make sure you have applied for the UTA account DCP configuration with your account manager
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/dcp-info
	GetAccountQueryDcpInfo(context.Context) (AccountQueryDcpInfo, error)

	// Set Collateral Coin
	//
	// You can decide whether the assets in the Unified account needs to be collateral coins.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/set-collateral
	AccountSetCollateralSwitch(context.Context, AccountSetCollateralSwitchParams) error

	// Set Margin Mode
	//
	// Default is regular margin mode
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/set-margin-mode
	AccountSetMarginMode(context.Context, AccountSetMarginModeParams) (AccountSetMarginModeResult, error)

	// Set Spot Hedging
	//
	// You can turn on/off Spot hedging feature in Portfolio margin
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/set-spot-hedge
	AccountSetHedgingMode(context.Context, AccountSetHedgingModeParams) (AccountSetHedgingModeResult, error)

	// Get Borrow History
	//
	// Get interest records, sorted in reverse order of creation time.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/borrow-history
	GetAccountBorrowHistory(context.Context, AccountBorrowHistoryQuery) (AccountBorrowHistory, error)

	// Batch Set Collateral Coin
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/batch-set-collateral
	AccountSetCollateralSwitchBatch(context.Context, AccountSetCollateralSwitchBatchParams) (AccountSetCollateralSwitchBatchResult, error)

	// Get Coin Greeks
	//
	// Get current account Greeks information
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/coin-greeks
	GetAssetCoinGreeks(context.Context, AssetCoinGreeksQuery) (AssetCoinGreeks, error)

	// Get MMP State
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/get-mmp-state
	GetAccountMmpState(context.Context, AccountMmpStateQuery) (AccountMmpState, error)

	// Reset MMP
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/reset-mmp
	AccountMmpReset(context.Context, AccountMmpResetParams) error

	// Set MMP
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/set-mmp
	AccountMmpModify(context.Context, AccountMmpModifyParams) error

	// Get SMP Group ID
	//
	// Query the SMP group ID of self match prevention
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/smp-group
	GetAccountSmpGroup(context.Context) (AccountSmpGroup, error)

	// Get Trade Behaviour Config
	//
	// Futures
	//
	// Spot
	//
	// Where x% is [priceLimitRatioX](/docs/v5/market/instrument); and y% is the [priceLimitRatioY](/docs/v5/market/instrument):
	//
	// You can get configuration how the system behaves when your limit order price exceeds the highest bid or lowest ask price.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/get-user-setting-config
	GetAccountUserSettingConfig(context.Context) (AccountUserSettingConfig, error)

	// Set Price Limit Behaviour
	//
	// Futures
	//
	// Spot
	//
	// Where x% is [priceLimitRatioX](/docs/v5/market/instrument); and y% is the [priceLimitRatioY](/docs/v5/market/instrument):
	//
	// You can configure how the system behaves when your limit order price exceeds the highest bid or lowest ask price. You can query your current configuration with [Get Trade Behaviour Setting](/docs/v5/account/get-user-setting-config). Learn more about the price limit for [spot](https://www.bybit.com/en/help-center/article/Bybit-Spot-Trading-Rules#A) and [futures](https://www.bybit.com/en/help-center/article?id=000002177#D) in the help centre.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/set-price-limit
	AccountSetLimitPxAction(context.Context, AccountSetLimitPxActionParams) error

	// Repay Liability
	//
	// You can manually repay the liabilities of Unified account
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/repay-liability
	AccountQuickRepayment(context.Context, AccountQuickRepaymentParams) (AccountQuickRepaymentResult, error)

	// Upgrade to Unified Account Pro
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/account/upgrade-unified-account
	AccountUpgradeToUta(context.Context) (AccountUpgradeToUtaResult, error)

	// Get Delivery Record
	//
	// Query delivery records of Invese Futures, USDC Futures, USDT Futures and Options, sorted by `deliveryTime` in descending order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/delivery
	GetAssetDeliveryRecord(context.Context, AssetDeliveryRecordQuery) (AssetDeliveryRecord, error)

	// Get USDC Session Settlement
	//
	// Query session settlement records of USDC perpetual and futures
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/settlement
	GetAssetSettlementRecord(context.Context, AssetSettlementRecordQuery) (AssetSettlementRecord, error)

	// Get Coin Exchange Records
	//
	// Query the coin exchange records.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/exchange
	GetAssetExchangeOrderRecord(context.Context, AssetExchangeOrderRecordQuery) (AssetExchangeOrderRecord, error)

	// Get Coin Info
	//
	// Query coin information, including chain information, withdraw and deposit status.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/coin-info
	GetAssetCoinQueryInfo(context.Context, AssetCoinQueryInfoQuery) (AssetCoinQueryInfo, error)

	// Get Sub UID
	//
	// Query the sub UIDs under a main UID. It returns up to 2000 sub accounts, if you need more, please call this [endpoint](/docs/v5/user/page-subuid).
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/sub-uid-list
	GetAssetTransferQuerySubMemberList(context.Context) (AssetTransferQuerySubMemberList, error)

	// Get Single Coin Balance
	//
	// Query the balance of a specific coin in a specific [account type](/docs/v5/enum#accounttype). Supports querying sub UID's balance. Also, you can check the transferable amount from master to sub account, sub to master account or sub to sub account, especially for user who has an institutional loan.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/balance/account-coin-balance
	GetAssetTransferQueryAccountCoinBalance(context.Context, AssetTransferQueryAccountCoinBalanceQuery) (AssetTransferQueryAccountCoinBalance, error)

	// Get All Coins Balance
	//
	// You could get all coin balance of all account types under the master account, and sub account.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/balance/all-balance
	GetAssetTransferQueryAccountCoinsBalance(context.Context, AssetTransferQueryAccountCoinsBalanceQuery) (AssetTransferQueryAccountCoinsBalance, error)

	// Get Withdrawable Amount
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/balance/delay-amount
	GetAssetWithdrawWithdrawableAmount(context.Context, AssetWithdrawWithdrawableAmountQuery) (AssetWithdrawWithdrawableAmount, error)

	// Create Internal Transfer
	//
	// Create the internal transfer between different [account types](/docs/v5/enum#accounttype) under the same UID.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/transfer/create-inter-transfer
	AssetTransferInterTransfer(context.Context, AssetTransferInterTransferParams) (AssetTransferInterTransferResult, error)

	// Get Internal Transfer Records
	//
	// Query the internal transfer records between different [account types](/docs/v5/enum#accounttype) under the same UID.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/transfer/inter-transfer-list
	GetAssetTransferQueryInterTransferList(context.Context, AssetTransferQueryInterTransferListQuery) (AssetTransferQueryInterTransferList, error)

	// Create Universal Transfer
	//
	// Transfer between sub-sub or main-sub.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/transfer/unitransfer
	AssetTransferUniversalTransfer(context.Context, AssetTransferUniversalTransferParams) (AssetTransferUniversalTransferResult, error)

	// Get Universal Transfer Records
	//
	// Query universal transfer records
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/transfer/unitransfer-list
	GetAssetTransferQueryUniversalTransferList(context.Context, AssetTransferQueryUniversalTransferListQuery) (AssetTransferQueryUniversalTransferList, error)

	// Get Transferable Coin
	//
	// Query the transferable coin list between each [account type](/docs/v5/enum#accounttype)
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/transfer/transferable-coin
	GetAssetTransferQueryTransferCoinList(context.Context, AssetTransferQueryTransferCoinListQuery) (AssetTransferQueryTransferCoinList, error)

	// Set Deposit Account
	//
	// Set auto transfer account after deposit. The same function as the setting for Deposit on [web GUI](https://www.bybit.com/app/user/settings)
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/deposit/set-deposit-acct
	AssetDepositDepositToAccount(context.Context, AssetDepositDepositToAccountParams) (AssetDepositDepositToAccountResult, error)

	// Get Deposit Records (on-chain)
	//
	// Query deposit records
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/deposit/deposit-record
	GetAssetDepositQueryRecord(context.Context, AssetDepositQueryRecordQuery) (AssetDepositQueryRecord, error)

	// Get Sub Deposit Records (on-chain)
	//
	// Query subaccount's deposit records by **main** UID's API key.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/deposit/sub-deposit-record
	GetAssetDepositQuerySubMemberRecord(context.Context, AssetDepositQuerySubMemberRecordQuery) (AssetDepositQuerySubMemberRecord, error)

	// Get Internal Deposit Records (off-chain)
	//
	// Query deposit records within the Bybit platform. These transactions are not on the blockchain.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/deposit/internal-deposit-record
	GetAssetDepositQueryInternalRecord(context.Context, AssetDepositQueryInternalRecordQuery) (AssetDepositQueryInternalRecord, error)

	// Get Master Deposit Address
	//
	// Query the deposit address information of MASTER account.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/deposit/master-deposit-addr
	GetAssetDepositQueryAddress(context.Context, AssetDepositQueryAddressQuery) (AssetDepositQueryAddress, error)

	// Get Sub Deposit Address
	//
	// Query the deposit address information of SUB account.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/deposit/sub-deposit-addr
	GetAssetDepositQuerySubMemberAddress(context.Context, AssetDepositQuerySubMemberAddressQuery) (AssetDepositQuerySubMemberAddress, error)

	// Get Withdrawal Address List
	//
	// Query the withdrawal addresses in the address book.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/withdraw/withdraw-address
	GetAssetWithdrawQueryAddress(context.Context, AssetWithdrawQueryAddressQuery) (AssetWithdrawQueryAddress, error)

	// Get Withdrawal Records
	//
	// Query withdrawal records.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/withdraw/withdraw-record
	GetAssetWithdrawQueryRecord(context.Context, AssetWithdrawQueryRecordQuery) (AssetWithdrawQueryRecord, error)

	// Get available VASPs
	//
	// This endpoint is used for query the available VASPs. This API distinguishes which compliance zone the user belongs to and the corresponding list of exchanges based on the user's UID.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/withdraw/vasp-list
	GetAssetWithdrawVaspList(context.Context) (AssetWithdrawVaspList, error)

	// Withdraw
	//
	// Note that, although the API rate limit for this endpoint is 5 req/s, there is also a secondary limit: you can only withdraw once every 10 seconds per chain/coin combination.
	//
	// Withdraw assets from your Bybit account. You can make an off-chain transfer if the target wallet address is from Bybit. This means that no blockchain fee will be charged.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/withdraw
	AssetWithdrawCreate(context.Context, AssetWithdrawCreateParams) (AssetWithdrawCreateResult, error)

	// Cancel Withdrawal
	//
	// Cancel the withdrawal
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/withdraw/cancel-withdraw
	AssetWithdrawCancel(context.Context, AssetWithdrawCancelParams) (AssetWithdrawCancelResult, error)

	// Get Convert Coin List
	//
	// Query for the list of coins you can convert to/from.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert/convert-coin-list
	GetAssetExchangeQueryCoinList(context.Context, AssetExchangeQueryCoinListQuery) (AssetExchangeQueryCoinList, error)

	// Request a Quote
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert/apply-quote
	AssetExchangeQuoteApply(context.Context, AssetExchangeQuoteApplyParams) (AssetExchangeQuoteApplyResult, error)

	// Confirm a Quote
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert/confirm-quote
	AssetExchangeConvertExecute(context.Context, AssetExchangeConvertExecuteParams) (AssetExchangeConvertExecuteResult, error)

	// Get Convert Status
	//
	// You can query the exchange result by sending quoteTxId.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert/get-convert-result
	GetAssetExchangeConvertResultQuery(context.Context, AssetExchangeConvertResultQueryQuery) (AssetExchangeConvertResultQuery, error)

	// Get Convert History
	//
	// Returns all confirmed quotes.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert/get-convert-history
	GetAssetExchangeQueryConvertHistory(context.Context, AssetExchangeQueryConvertHistoryQuery) (AssetExchangeQueryConvertHistory, error)

	// Get Small Balance Coins
	//
	// Query small-balance coins with a USDT equivalent of less than 10 USDT, and ensure that the total amount for each conversion transaction is between 1.0e-8 and 200 USDT.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert-small-balance/small-balanc-coins
	GetAssetCovertSmallBalanceList(context.Context, AssetCovertSmallBalanceListQuery) (AssetCovertSmallBalanceList, error)

	// Request a Quote
	//
	// Custody accounts, like copper, fireblock, etc are **not supported** to make a convertion
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert-small-balance/request-quote
	AssetCovertGetQuote(context.Context, AssetCovertGetQuoteParams) (AssetCovertGetQuoteResult, error)

	// Confirm a Quote
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert-small-balance/confirm-quote
	AssetCovertSmallBalanceExecute(context.Context, AssetCovertSmallBalanceExecuteParams) (AssetCovertSmallBalanceExecuteResult, error)

	// Get Exchange History
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/convert-small-balance/exchange-history
	GetAssetCovertSmallBalanceHistory(context.Context, AssetCovertSmallBalanceHistoryQuery) (AssetCovertSmallBalanceHistory, error)

	// Get Trading Pair List
	//
	// Query for the list of coins you can convert to/from.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/query-coin-list
	GetFiatQueryCoinList(context.Context, FiatQueryCoinListQuery) (FiatQueryCoinList, error)

	// Get Reference Price
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/reference-price
	GetFiatReferencePrice(context.Context, FiatReferencePriceQuery) (FiatReferencePrice, error)

	// Request a Quote
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/quote-apply
	FiatQuoteApply(context.Context, FiatQuoteApplyParams) (FiatQuoteApplyResult, error)

	// Confirm a Quote
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/confirm-quote
	FiatTradeExecute(context.Context, FiatTradeExecuteParams) (FiatTradeExecuteResult, error)

	// Get Convert Status
	//
	// Returns the details of this convert.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/query-trade
	GetFiatTradeQuery(context.Context, FiatTradeQueryQuery) (FiatTradeQuery, error)

	// Get Convert History
	//
	// Returns all the convert history
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/query-trade-history
	GetFiatQueryTradeHistory(context.Context, FiatQueryTradeHistoryQuery) (FiatQueryTradeHistory, error)

	// Get Balance
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/asset/fiat-convert/balance-query
	GetFiatBalanceQuery(context.Context, FiatBalanceQueryQuery) (FiatBalanceQuery, error)

	// Create Sub UID
	//
	// Create a new sub user id. Use **master** account's api key.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/create-subuid
	UserCreateSubMember(context.Context, UserCreateSubMemberParams) (UserCreateSubMemberResult, error)

	// Create Sub UID API Key
	//
	// To create new API key for those newly created sub UID. Use **master user's api key** **only**.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/create-subuid-apikey
	UserCreateSubApi(context.Context, UserCreateSubApiParams) (UserCreateSubApiResult, error)

	// Get Sub UID List (Limited)
	//
	// Get at most 10k sub UID of master account. Use **master user's api key** **only**.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/subuid-list
	GetUserQuerySubMembers(context.Context) (UserQuerySubMembers, error)

	// Get Sub UID List (Unlimited)
	//
	// This API is applicable to the client who has over 10k sub accounts. Use **master user's api key** **only**.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/page-subuid
	GetUserSubmembers(context.Context, UserSubmembersQuery) (UserSubmembers, error)

	// Get Fund Custodial Sub Acct
	//
	// The institutional client can query the fund custodial sub accounts.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/fund-subuid-list
	GetUserEscrowSubMembers(context.Context, UserEscrowSubMembersQuery) (UserEscrowSubMembers, error)

	// Freeze Sub UID
	//
	// Freeze Sub UID. Use **master user's api key** **only**.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/froze-subuid
	UserFrozenSubMember(context.Context, UserFrozenSubMemberParams) error

	// Get API Key Information
	//
	// Get the information of the api key. Use the api key pending to be checked to call the endpoint. Both **master and sub user's api key** are applicable.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/apikey-info
	GetUserQueryApi(context.Context) (UserQueryApi, error)

	// Get Sub Account All API Keys
	//
	// Query all api keys information of a sub UID.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/list-sub-apikeys
	GetUserSubApikeys(context.Context, UserSubApikeysQuery) (UserSubApikeys, error)

	// Get UID Wallet Type
	//
	// Get available wallet types for the master account or sub account
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/wallet-type
	GetUserGetMemberType(context.Context, UserGetMemberTypeQuery) (UserGetMemberType, error)

	// Modify Master API Key
	//
	// Modify the settings of master api key. Use the api key pending to be modified to call the endpoint. Use **master user's api key** **only**.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/modify-master-apikey
	UserUpdateApi(context.Context, UserUpdateApiParams) (UserUpdateApiResult, error)

	// Modify Sub API Key
	//
	// Modify the settings of sub api key. Use the sub account api key pending to be modified to call the endpoint or use master account api key to manage its sub account api key.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/modify-sub-apikey
	UserUpdateSubApi(context.Context, UserUpdateSubApiParams) (UserUpdateSubApiResult, error)

	// Delete Sub UID
	//
	// Delete a sub UID. Before deleting the UID, please make sure there is no asset.
	// Use **master** user's api key\*\*.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/rm-subuid
	UserDelSubmember(context.Context, UserDelSubmemberParams) error

	// Delete Master API Key
	//
	// Delete the api key of master account. Use the api key pending to be delete to call the endpoint. Use **master user's api key** **only**.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/rm-master-apikey
	UserDeleteApi(context.Context) error

	// Delete Sub API Key
	//
	// Delete the api key of sub account. Use the sub api key pending to be delete to call the endpoint or use the master api key to delete corresponding sub account api key
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/user/rm-sub-apikey
	UserDeleteSubApi(context.Context, UserDeleteSubApiParams) error

	// Get Instruments Info
	//
	// Query for the instrument specification of spread combinations.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/market/instrument
	GetSpreadInstrument(context.Context, SpreadInstrumentQuery) (SpreadInstrument, error)

	// Get Orderbook
	//
	// Query spread orderbook depth data.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/market/orderbook
	GetSpreadOrderbook(context.Context, SpreadOrderbookQuery) (SpreadOrderbook, error)

	// Get Tickers
	//
	// Query for the latest price snapshot, best bid/ask price, and trading volume of different spread combinations in the last 24 hours.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/market/tickers
	GetSpreadTickers(context.Context, SpreadTickersQuery) (SpreadTickers, error)

	// Get Recent Public Trades
	//
	// Query recent public spread trading history in Bybit.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/market/recent-trade
	GetSpreadRecentTrade(context.Context, SpreadRecentTradeQuery) (SpreadRecentTrade, error)

	// Create Order
	//
	// Place a spread combination order. **Up to 50 open orders** per account.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/trade/create-order
	SpreadOrderCreate(context.Context, SpreadOrderCreateParams) (SpreadOrderCreateResult, error)

	// Amend Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/trade/amend-order
	SpreadOrderAmend(context.Context, SpreadOrderAmendParams) (SpreadOrderAmendResult, error)

	// Cancel Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/trade/cancel-order
	SpreadOrderCancel(context.Context, SpreadOrderCancelParams) (SpreadOrderCancelResult, error)

	// Cancel All Orders
	//
	// Cancel all open orders
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/trade/cancel-all
	SpreadOrderCancelAll(context.Context, SpreadOrderCancelAllParams) (SpreadOrderCancelAllResult, error)

	// Get Open Orders
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/trade/open-order
	GetSpreadOrderRealtime(context.Context, SpreadOrderRealtimeQuery) (SpreadOrderRealtime, error)

	// Get Order History
	//
	// **Single leg orders can also be found with "createType"=`CreateByFutureSpread` via [Get Order History](/docs/v5/order/order-list)**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/trade/order-history
	GetSpreadOrderHistory(context.Context, SpreadOrderHistoryQuery) (SpreadOrderHistory, error)

	// Get Trade History
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spread/trade/trade-history
	GetSpreadExecutionList(context.Context, SpreadExecutionListQuery) (SpreadExecutionList, error)

	// Create RFQ
	//
	// Create RFQ. **Up to 50 requests** per second.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/create-rfq
	RfqCreateRfq(context.Context, RfqCreateRfqParams) (RfqCreateRfqResult, error)

	// Get RFQ Configuration
	//
	// RFQ Config. **Up to 50 requests** per second.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/rfq-config
	GetRfqConfig(context.Context) (RfqConfig, error)

	// Cancel RFQ
	//
	// Cancel RFQ. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/cancel-rfq
	RfqCancelRfq(context.Context, RfqCancelRfqParams) (RfqCancelRfqResult, error)

	// Cancel All RFQs
	//
	// Cancel all active RFQs. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/cancel-all-rfq
	RfqCancelAllRfq(context.Context) (RfqCancelAllRfqResult, error)

	// Accept non-LP Quote
	//
	// Accept non-LP Quote. **Up to 50 requests** per second.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/accept-other-quote
	RfqAcceptOtherQuote(context.Context, RfqAcceptOtherQuoteParams) (RfqAcceptOtherQuoteResult, error)

	// Create Quote
	//
	// Create a quote. **Up to 50 requests** per second. The quoting party sends a quote in response to the inquirier.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/create-quote
	RfqCreateQuote(context.Context, RfqCreateQuoteParams) (RfqCreateQuoteResult, error)

	// Execute Quote
	//
	// Execute quote – only for the creator of the RFQ. **Up to 50 requests** per second.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/execute-quote
	RfqExecuteQuote(context.Context, RfqExecuteQuoteParams) (RfqExecuteQuoteResult, error)

	// Cancel Quote
	//
	// Cancel a quote. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/cancel-quote
	RfqCancelQuote(context.Context, RfqCancelQuoteParams) (RfqCancelQuoteResult, error)

	// Cancel All Quotes
	//
	// Cancel all active quotes. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/cancel-all-quotes
	RfqCancelAllQuotes(context.Context) (RfqCancelAllQuotesResult, error)

	// Get RFQs (real-time)
	//
	// Obtain real-time inquiry information. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/rfq-realtime
	GetRfqRfqRealtime(context.Context, RfqRfqRealtimeQuery) (RfqRfqRealtime, error)

	// Get RFQs
	//
	// Obtain historical inquiry information. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/rfq-list
	GetRfqRfqList(context.Context, RfqRfqListQuery) (RfqRfqList, error)

	// Get Quotes (real-time)
	//
	// Get real-time quote information. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/quote-realtime
	GetRfqQuoteRealtime(context.Context, RfqQuoteRealtimeQuery) (RfqQuoteRealtime, error)

	// Get Quotes
	//
	// Obtain historical quote information. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/quote-list
	GetRfqQuoteList(context.Context, RfqQuoteListQuery) (RfqQuoteList, error)

	// Get Trade History
	//
	// Obtain transaction information. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/trade-list
	GetRfqTradeList(context.Context, RfqTradeListQuery) (RfqTradeList, error)

	// Get Public Trades
	//
	// Get the recently executed rfq successfully. **Up to 50 requests per second**
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/rfq/trade/public-trades
	GetRfqPublicTrades(context.Context, RfqPublicTradesQuery) (RfqPublicTrades, error)

	// Get Tiered Collateral Ratio
	//
	// UTA loan tiered collateral ratio
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/tier-collateral-ratio
	GetSpotMarginTradeCollateral(context.Context, SpotMarginTradeCollateralQuery) (SpotMarginTradeCollateral, error)

	// Get Historical Interest Rate
	//
	// You can query up to six months borrowing interest rate of Margin trading.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/historical-interest
	GetSpotMarginTradeInterestRateHistory(context.Context, SpotMarginTradeInterestRateHistoryQuery) (SpotMarginTradeInterestRateHistory, error)

	// Toggle Margin Trade
	//
	// Turn on / off spot margin trade
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/switch-mode
	SpotMarginTradeSwitchMode(context.Context, SpotMarginTradeSwitchModeParams) (SpotMarginTradeSwitchModeResult, error)

	// Set Leverage
	//
	// Set the user's maximum leverage in spot cross margin
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/set-leverage
	SpotMarginTradeSetLeverage(context.Context, SpotMarginTradeSetLeverageParams) error

	// Get Status And Leverage
	//
	// Query the Spot margin status and leverage
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/status
	GetSpotMarginTradeState(context.Context) (SpotMarginTradeState, error)

	// Get Max Borrowable Amount
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/max-borrowable
	GetSpotMarginTradeMaxBorrowable(context.Context, SpotMarginTradeMaxBorrowableQuery) (SpotMarginTradeMaxBorrowable, error)

	// Get Position Tiers
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/position-tiers
	GetSpotMarginTradePositionTiers(context.Context, SpotMarginTradePositionTiersQuery) (SpotMarginTradePositionTiers, error)

	// Get Coin State
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/coinstate
	GetSpotMarginTradeCoinstate(context.Context, SpotMarginTradeCoinstateQuery) (SpotMarginTradeCoinstate, error)

	// Get Available Amount to Repay
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/repayment-available-amount
	GetSpotMarginTradeRepaymentAvailableAmount(context.Context, SpotMarginTradeRepaymentAvailableAmountQuery) (SpotMarginTradeRepaymentAvailableAmount, error)

	// Set Auto Repay Mode
	//
	// Set spot automatic repayment mode
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/set-auto-repay-mode
	SpotMarginTradeSetAutoRepayMode(context.Context, SpotMarginTradeSetAutoRepayModeParams) (SpotMarginTradeSetAutoRepayModeResult, error)

	// Get Auto Repay Mode
	//
	// Get spot automatic repayment mode
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/spot-margin-uta/get-auto-repay-mode
	GetSpotMarginTradeGetAutoRepayMode(context.Context, SpotMarginTradeGetAutoRepayModeQuery) (SpotMarginTradeGetAutoRepayMode, error)

	// Get Borrowable Coins
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/loan-coin
	GetCryptoLoanCommonLoanableData(context.Context, CryptoLoanCommonLoanableDataQuery) (CryptoLoanCommonLoanableData, error)

	// Get Collateral Coins
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/collateral-coin
	GetCryptoLoanCommonCollateralData(context.Context, CryptoLoanCommonCollateralDataQuery) (CryptoLoanCommonCollateralData, error)

	// Get Max. Allowed Collateral Reduction Amount
	//
	// Retrieve the maximum redeemable amount of your collateral asset based on LTV.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/reduce-max-collateral-amt
	GetCryptoLoanCommonMaxCollateralAmount(context.Context, CryptoLoanCommonMaxCollateralAmountQuery) (CryptoLoanCommonMaxCollateralAmount, error)

	// Adjust Collateral Amount
	//
	// You can increase or reduce your collateral amount. When you reduce, please obey the [Get Max. Allowed Collateral Reduction Amount](/docs/v5/new-crypto-loan/reduce-max-collateral-amt)
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/adjust-collateral
	CryptoLoanCommonAdjustLtv(context.Context, CryptoLoanCommonAdjustLtvParams) (CryptoLoanCommonAdjustLtvResult, error)

	// Get Collateral Adjustment History
	//
	// Query for your LTV adjustment history.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/ltv-adjust-history
	GetCryptoLoanCommonAdjustmentHistory(context.Context, CryptoLoanCommonAdjustmentHistoryQuery) (CryptoLoanCommonAdjustmentHistory, error)

	// Get Crypto Loan Position
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/crypto-loan-position
	GetCryptoLoanCommonPosition(context.Context) (CryptoLoanCommonPosition, error)

	// Obtain Max Loan Amount
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/max-loan-amt
	CryptoLoanCommonMaxLoan(context.Context, CryptoLoanCommonMaxLoanParams) (CryptoLoanCommonMaxLoanResult, error)

	// Borrow
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/flexible/borrow
	CryptoLoanFlexibleBorrow(context.Context, CryptoLoanFlexibleBorrowParams) (CryptoLoanFlexibleBorrowResult, error)

	// Repay
	//
	// Fully or partially repay a loan. If interest is due, that is paid off first, with the loaned amount being paid off only after due interest.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/flexible/repay
	CryptoLoanFlexibleRepay(context.Context, CryptoLoanFlexibleRepayParams) (CryptoLoanFlexibleRepayResult, error)

	// Collateral Repayment
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/flexible/repay-collateral
	CryptoLoanFlexibleRepayCollateral(context.Context, CryptoLoanFlexibleRepayCollateralParams) error

	// Get Flexible Loans
	//
	// Query for your ongoing loans
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/flexible/unpaid-loan-order
	GetCryptoLoanFlexibleOngoingCoin(context.Context, CryptoLoanFlexibleOngoingCoinQuery) (CryptoLoanFlexibleOngoingCoin, error)

	// Get Borrowing History
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/flexible/loan-orders
	GetCryptoLoanFlexibleBorrowHistory(context.Context, CryptoLoanFlexibleBorrowHistoryQuery) (CryptoLoanFlexibleBorrowHistory, error)

	// Get Repayment History
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/flexible/repay-orders
	GetCryptoLoanFlexibleRepaymentHistory(context.Context, CryptoLoanFlexibleRepaymentHistoryQuery) (CryptoLoanFlexibleRepaymentHistory, error)

	// Get Lending Market
	//
	// If you want to supply, you can use this endpoint to check whether there are any suitable counterparty borrow orders available.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/supply-market
	GetCryptoLoanFixedSupplyOrderQuote(context.Context, CryptoLoanFixedSupplyOrderQuoteQuery) (CryptoLoanFixedSupplyOrderQuote, error)

	// Get Borrowing Market
	//
	// If you want to borrow, you can use this endpoint to check whether there are any suitable counterparty supply orders available.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/borrow-market
	GetCryptoLoanFixedBorrowOrderQuote(context.Context, CryptoLoanFixedBorrowOrderQuoteQuery) (CryptoLoanFixedBorrowOrderQuote, error)

	// Create Borrow Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/borrow
	CryptoLoanFixedBorrow(context.Context, CryptoLoanFixedBorrowParams) (CryptoLoanFixedBorrowResult, error)

	// Renew Borrow Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/renew
	CryptoLoanFixedRenew(context.Context, CryptoLoanFixedRenewParams) (CryptoLoanFixedRenewResult, error)

	// Create Supply Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/supply
	CryptoLoanFixedSupply(context.Context, CryptoLoanFixedSupplyParams) (CryptoLoanFixedSupplyResult, error)

	// Cancel Borrow Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/cancel-borrow
	CryptoLoanFixedBorrowOrderCancel(context.Context, CryptoLoanFixedBorrowOrderCancelParams) error

	// Cancel Supply Order
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/cancel-supply
	CryptoLoanFixedSupplyOrderCancel(context.Context, CryptoLoanFixedSupplyOrderCancelParams) error

	// Get Borrow Contract Info
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/borrow-contract
	GetCryptoLoanFixedBorrowContractInfo(context.Context, CryptoLoanFixedBorrowContractInfoQuery) (CryptoLoanFixedBorrowContractInfo, error)

	// Get Supply Contract Info
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/supply-contract copy
	GetCryptoLoanFixedSupplyContractInfo(context.Context, CryptoLoanFixedSupplyContractInfoQuery) (CryptoLoanFixedSupplyContractInfo, error)

	// Get Borrow Order Info
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/borrow-order
	GetCryptoLoanFixedBorrowOrderInfo(context.Context, CryptoLoanFixedBorrowOrderInfoQuery) (CryptoLoanFixedBorrowOrderInfo, error)

	// Get Renew Order Info
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/renew-order
	GetCryptoLoanFixedRenewInfo(context.Context, CryptoLoanFixedRenewInfoQuery) (CryptoLoanFixedRenewInfo, error)

	// Get Supply Order Info
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/supply-order
	GetCryptoLoanFixedSupplyOrderInfo(context.Context, CryptoLoanFixedSupplyOrderInfoQuery) (CryptoLoanFixedSupplyOrderInfo, error)

	// Repay
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/repay
	CryptoLoanFixedFullyRepay(context.Context, CryptoLoanFixedFullyRepayParams) (CryptoLoanFixedFullyRepayResult, error)

	// Collateral Repayment
	//
	// There are limits on the repayment amount in a single transaction. Please read this [announcement](https://announcements.bybit.com/article/crypto-loan-manual-repayment-update-bltde33509ddde5e8fd/) before repaying with collateral.
	// When repaying with collateral, Bybit will charge a repayment fee. The applicable fee rate is the higher of the repayment fee rates for the collateral asset and the debt asset. You can call this endpoint: [View fee rates by asset](https://www.bybit.com/x-api/spot/api/fixed-loan/v1/coin-config) to get "reapyFee" where "pledgeEnable" = 1 for coins' repayment fee rates.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/repay-collateral
	CryptoLoanFixedRepayCollateral(context.Context, CryptoLoanFixedRepayCollateralParams) error

	// Get Repayment History
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/repay-history
	GetCryptoLoanFixedRepaymentHistory(context.Context, CryptoLoanFixedRepaymentHistoryQuery) (CryptoLoanFixedRepaymentHistory, error)

	// Get Collateral Coins
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/collateral-coin
	GetCryptoLoanCollateralData(context.Context, CryptoLoanCollateralDataQuery) (CryptoLoanCollateralData, error)

	// Get Borrowable Coins
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/loan-coin
	GetCryptoLoanLoanableData(context.Context, CryptoLoanLoanableDataQuery) (CryptoLoanLoanableData, error)

	// Get Account Borrowable/Collateralizable Limit
	//
	// Query for the minimum and maximum amounts your account can borrow and how much collateral you can put up.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/acct-borrow-collateral
	GetCryptoLoanBorrowableCollateralisableNumber(context.Context, CryptoLoanBorrowableCollateralisableNumberQuery) (CryptoLoanBorrowableCollateralisableNumber, error)

	// Repay
	//
	// Fully or partially repay a loan. If interest is due, that is paid off first, with the loaned amount being paid off only after due interest.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/repay
	CryptoLoanRepay(context.Context, CryptoLoanRepayParams) (CryptoLoanRepayResult, error)

	// Get Unpaid Loans
	//
	// Query for your ongoing loans.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/unpaid-loan-order
	GetCryptoLoanOngoingOrders(context.Context, CryptoLoanOngoingOrdersQuery) (CryptoLoanOngoingOrders, error)

	// Get Loan Repayment History
	//
	// Query for loan repayment transactions. A loan may be repaid in multiple repayments.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/repay-transaction
	GetCryptoLoanRepaymentHistory(context.Context, CryptoLoanRepaymentHistoryQuery) (CryptoLoanRepaymentHistory, error)

	// Get Completed Loan History
	//
	// Query for the last 6 months worth of your completed (fully paid off) loans.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/completed-loan-order
	GetCryptoLoanBorrowHistory(context.Context, CryptoLoanBorrowHistoryQuery) (CryptoLoanBorrowHistory, error)

	// Get Max. Allowed Collateral Reduction Amount
	//
	// Query for the maximum amount by which collateral may be reduced by.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/reduce-max-collateral-amt
	GetCryptoLoanMaxCollateralAmount(context.Context, CryptoLoanMaxCollateralAmountQuery) (CryptoLoanMaxCollateralAmount, error)

	// Adjust Collateral Amount
	//
	// You can increase or reduce your collateral amount. When you reduce, please obey the [max. allowed reduction amount](https://bybit-exchange.github.io/docs/v5/crypto-loan/reduce-max-collateral-amt).
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/adjust-collateral
	CryptoLoanAdjustLtv(context.Context, CryptoLoanAdjustLtvParams) (CryptoLoanAdjustLtvResult, error)

	// Get Loan LTV Adjustment History
	//
	// Query for your LTV adjustment history.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/crypto-loan/ltv-adjust-history
	GetCryptoLoanAdjustmentHistory(context.Context, CryptoLoanAdjustmentHistoryQuery) (CryptoLoanAdjustmentHistory, error)

	// Get Product Info
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/otc/margin-product-info
	GetInsLoanProductInfos(context.Context, InsLoanProductInfosQuery) (InsLoanProductInfos, error)

	// Get Margin Coin Info
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/otc/margin-coin-convert-info
	GetInsLoanEnsureTokensConvert(context.Context, InsLoanEnsureTokensConvertQuery) (InsLoanEnsureTokensConvert, error)

	// Get Loan Orders
	//
	// Get up to 2 years worth of historical loan orders.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/otc/loan-info
	GetInsLoanLoanOrder(context.Context, InsLoanLoanOrderQuery) (InsLoanLoanOrder, error)

	// Get Repayment Orders
	//
	// Get a list of your loan repayment orders (orders which repaid the loan).
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/otc/repay-info
	GetInsLoanRepaidHistory(context.Context, InsLoanRepaidHistoryQuery) (InsLoanRepaidHistory, error)

	// Get LTV
	//
	// Get your loan-to-value (LTV) ratio.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/otc/ltv-convert
	GetInsLoanLtvConvert(context.Context) (InsLoanLtvConvert, error)

	// Bind Or Unbind UID
	//
	// For the institutional loan product, you can bind new UIDs to the risk unit or unbind UID from the risk unit.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/otc/bind-uid
	InsLoanAssociationUid(context.Context, InsLoanAssociationUidParams) (InsLoanAssociationUidResult, error)

	// Repay
	//
	// You can repay the INS loan by calling this API.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/otc/repay
	InsLoanRepayLoan(context.Context, InsLoanRepayLoanParams) (InsLoanRepayLoanResult, error)

	// Get Earning
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/exchange-earning
	GetBrokerEarningsInfo(context.Context, BrokerEarningsInfoQuery) (BrokerEarningsInfo, error)

	// Get Account Info
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/account-info
	GetBrokerAccountInfo(context.Context) (BrokerAccountInfo, error)

	// Get Sub Account Deposit Records
	//
	// Exchange broker can query subaccount's deposit records by **main** UID's API key without specifying uid.
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/sub-deposit-record
	GetBrokerAssetQuerySubMemberDepositRecord(context.Context, BrokerAssetQuerySubMemberDepositRecordQuery) (BrokerAssetQuerySubMemberDepositRecord, error)

	// Set Rate Limit
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/rate-limit/set
	BrokerApilimitSet(context.Context, BrokerApilimitSetParams) (BrokerApilimitSetResult, error)

	// Get Rate Limit Cap
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/rate-limit/query-cap
	GetBrokerApilimitQueryCap(context.Context) (BrokerApilimitQueryCap, error)

	// Get All Rate Limits
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/exchange-broker/rate-limit/query-all
	GetBrokerApilimitQueryAll(context.Context, BrokerApilimitQueryAllQuery) (BrokerApilimitQueryAll, error)

	// Get Voucher Spec
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/reward/voucher
	BrokerAwardInfo(context.Context, BrokerAwardInfoParams) (BrokerAwardInfoResult, error)

	// Issue Voucher
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/reward/issue-voucher
	BrokerAwardDistributeAward(context.Context, BrokerAwardDistributeAwardParams) error

	// Get Issued Voucher
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/broker/reward/get-issue-voucher
	BrokerAwardDistributionRecord(context.Context, BrokerAwardDistributionRecordParams) (BrokerAwardDistributionRecordResult, error)

	// Get Product Info
	//
	// [Bybit Saving FAQ](https://www.bybit.com/en/help-center/article/FAQ-Bybit-Savings)
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/earn/product-info
	GetEarnProduct(context.Context, EarnProductQuery) (EarnProduct, error)

	// Stake / Redeem
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/earn/create-order
	EarnPlaceOrder(context.Context, EarnPlaceOrderParams) (EarnPlaceOrderResult, error)

	// Get Stake/Redeem Order History
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/earn/order-history
	GetEarnOrder(context.Context, EarnOrderQuery) (EarnOrder, error)

	// Get Staked Position
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/earn/position
	GetEarnPosition(context.Context, EarnPositionQuery) (EarnPosition, error)

	// Get Yield History
	//
	// You can get the past 3 months data
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/earn/yield-history
	GetEarnYield(context.Context, EarnYieldQuery) (EarnYield, error)

	// Get Hourly Yield History
	//
	// Doc: https://bybit-exchange.github.io/docs/v5/earn/hourly-yield
	GetEarnHourlyYield(context.Context, EarnHourlyYieldQuery) (EarnHourlyYield, error)
}
