// Code generated by fullpipe. DO NOT EDIT.

package bybit

type BizType string

const (
	BizTypeSpot        BizType = "SPOT"
	BizTypeDerivatives BizType = "DERIVATIVES"
	BizTypeOptions     BizType = "OPTIONS"
)

type IntervalTime string

const (
	IntervalTime5Min  IntervalTime = "5min"
	IntervalTime15Min IntervalTime = "15min"
	IntervalTime30Min IntervalTime = "30min"
	IntervalTime1H    IntervalTime = "1h"
	IntervalTime4H    IntervalTime = "4h"
	IntervalTime1D    IntervalTime = "1d"
)

type AnnouncementType string

const (
	AnnouncementTypeNewCrypto          AnnouncementType = "new_crypto"
	AnnouncementTypeLatestBybitNews    AnnouncementType = "latest_bybit_news"
	AnnouncementTypeDelistings         AnnouncementType = "delistings"
	AnnouncementTypeLatestActivities   AnnouncementType = "latest_activities"
	AnnouncementTypeProductUpdates     AnnouncementType = "product_updates"
	AnnouncementTypeMaintenanceUpdates AnnouncementType = "maintenance_updates"
	AnnouncementTypeNewFiatListings    AnnouncementType = "new_fiat_listings"
	AnnouncementTypeOther              AnnouncementType = "other"
)

type OrderStatus string

const (
	OrderStatusNew                     OrderStatus = "New"
	OrderStatusPartiallyFilled         OrderStatus = "PartiallyFilled"
	OrderStatusUntriggered             OrderStatus = "Untriggered"
	OrderStatusRejected                OrderStatus = "Rejected"
	OrderStatusPartiallyFilledCanceled OrderStatus = "PartiallyFilledCanceled"
	OrderStatusFilled                  OrderStatus = "Filled"
	OrderStatusCancelled               OrderStatus = "Cancelled"
	OrderStatusTriggered               OrderStatus = "Triggered"
	OrderStatusDeactivated             OrderStatus = "Deactivated"
)

type SbeRejectReason string

const (
	SbeRejectReason0   SbeRejectReason = "0"
	SbeRejectReason1   SbeRejectReason = "1"
	SbeRejectReason2   SbeRejectReason = "2"
	SbeRejectReason3   SbeRejectReason = "3"
	SbeRejectReason4   SbeRejectReason = "4"
	SbeRejectReason5   SbeRejectReason = "5"
	SbeRejectReason6   SbeRejectReason = "6"
	SbeRejectReason7   SbeRejectReason = "7"
	SbeRejectReason8   SbeRejectReason = "8"
	SbeRejectReason9   SbeRejectReason = "9"
	SbeRejectReason10  SbeRejectReason = "10"
	SbeRejectReason11  SbeRejectReason = "11"
	SbeRejectReason12  SbeRejectReason = "12"
	SbeRejectReason13  SbeRejectReason = "13"
	SbeRejectReason14  SbeRejectReason = "14"
	SbeRejectReason15  SbeRejectReason = "15"
	SbeRejectReason16  SbeRejectReason = "16"
	SbeRejectReason17  SbeRejectReason = "17"
	SbeRejectReason18  SbeRejectReason = "18"
	SbeRejectReason19  SbeRejectReason = "19"
	SbeRejectReason20  SbeRejectReason = "20"
	SbeRejectReason21  SbeRejectReason = "21"
	SbeRejectReason22  SbeRejectReason = "22"
	SbeRejectReason23  SbeRejectReason = "23"
	SbeRejectReason24  SbeRejectReason = "24"
	SbeRejectReason25  SbeRejectReason = "25"
	SbeRejectReason28  SbeRejectReason = "28"
	SbeRejectReason29  SbeRejectReason = "29"
	SbeRejectReason30  SbeRejectReason = "30"
	SbeRejectReason31  SbeRejectReason = "31"
	SbeRejectReason34  SbeRejectReason = "34"
	SbeRejectReason35  SbeRejectReason = "35"
	SbeRejectReason36  SbeRejectReason = "36"
	SbeRejectReason100 SbeRejectReason = "100"
	SbeRejectReason101 SbeRejectReason = "101"
	SbeRejectReason102 SbeRejectReason = "102"
	SbeRejectReason103 SbeRejectReason = "103"
	SbeRejectReason104 SbeRejectReason = "104"
	SbeRejectReason105 SbeRejectReason = "105"
	SbeRejectReason106 SbeRejectReason = "106"
	SbeRejectReason107 SbeRejectReason = "107"
	SbeRejectReason108 SbeRejectReason = "108"
	SbeRejectReason110 SbeRejectReason = "110"
	SbeRejectReason111 SbeRejectReason = "111"
	SbeRejectReason112 SbeRejectReason = "112"
	SbeRejectReason113 SbeRejectReason = "113"
	SbeRejectReason200 SbeRejectReason = "200"
)

type Category string

const (
	CategorySpot    Category = "spot"
	CategoryLinear  Category = "linear"
	CategoryInverse Category = "inverse"
	CategoryOption  Category = "option"
)

type TriggerBy string

const (
	TriggerByLastPrice  TriggerBy = "LastPrice"
	TriggerByIndexPrice TriggerBy = "IndexPrice"
	TriggerByMarkPrice  TriggerBy = "MarkPrice"
)

type CurAuctionPhase string

const (
	CurAuctionPhaseNotStarted          CurAuctionPhase = "NotStarted"
	CurAuctionPhaseFinished            CurAuctionPhase = "Finished"
	CurAuctionPhaseCallAuction         CurAuctionPhase = "CallAuction"
	CurAuctionPhaseCallAuctionNoCancel CurAuctionPhase = "CallAuctionNoCancel"
	CurAuctionPhaseCrossMatching       CurAuctionPhase = "CrossMatching"
	CurAuctionPhaseContinuousTrading   CurAuctionPhase = "ContinuousTrading"
)

type GroupId string

const (
	GroupId1 GroupId = "1"
	GroupId2 GroupId = "2"
	GroupId3 GroupId = "3"
	GroupId4 GroupId = "4"
	GroupId5 GroupId = "5"
	GroupId6 GroupId = "6"
	GroupId7 GroupId = "7"
	GroupId8 GroupId = "8"
)

type GroupName string

const (
	GroupNameG1MajorCoins        GroupName = "G1(Major Coins)"
	GroupNameG2HighGrowth        GroupName = "G2(High Growth)"
	GroupNameG3MidTierLiquidity  GroupName = "G3(Mid-Tier Liquidity)"
	GroupNameG4MidTierActivation GroupName = "G4(Mid-Tier Activation)"
	GroupNameG5LongTail          GroupName = "G5(Long Tail)"
	GroupNameInnovationZone      GroupName = "Innovation-Zone"
	GroupNamePreListing          GroupName = "Pre-listing"
	GroupNameUsdc                GroupName = "USDC"
)

type SpotFeeCurrencyInstruction string

const ()

type SbeOrderStatus string

const (
	SbeOrderStatus5 SbeOrderStatus = "5"
	SbeOrderStatus6 SbeOrderStatus = "6"
	SbeOrderStatus7 SbeOrderStatus = "7"
	SbeOrderStatus8 SbeOrderStatus = "8"
	SbeOrderStatus9 SbeOrderStatus = "9"
	SbeOrderStatus0 SbeOrderStatus = "0"
)

type Interval string

const (
	Interval1   Interval = "1"
	Interval3   Interval = "3"
	Interval5   Interval = "5"
	Interval15  Interval = "15"
	Interval30  Interval = "30"
	Interval60  Interval = "60"
	Interval120 Interval = "120"
	Interval240 Interval = "240"
	Interval360 Interval = "360"
	Interval720 Interval = "720"
	IntervalD   Interval = "D"
	IntervalW   Interval = "W"
	IntervalM   Interval = "M"
)

type PositionIdx string

const (
	PositionIdx0 PositionIdx = "0"
	PositionIdx1 PositionIdx = "1"
	PositionIdx2 PositionIdx = "2"
)

type ExecType string

const (
	ExecTypeTrade        ExecType = "Trade"
	ExecTypeAdlTrade     ExecType = "AdlTrade"
	ExecTypeFunding      ExecType = "Funding"
	ExecTypeBustTrade    ExecType = "BustTrade"
	ExecTypeDelivery     ExecType = "Delivery"
	ExecTypeSettle       ExecType = "Settle"
	ExecTypeBlockTrade   ExecType = "BlockTrade"
	ExecTypeMovePosition ExecType = "MovePosition"
	ExecTypeFutureSpread ExecType = "FutureSpread"
	ExecTypeUnknown      ExecType = "UNKNOWN"
)

type OrderType string

const (
	OrderTypeMarket   OrderType = "Market"
	OrderTypeLimit    OrderType = "Limit"
	OrderTypeUnknown  OrderType = "UNKNOWN"
	OrderTypeExecType OrderType = "execType"
	OrderTypeFunding  OrderType = "Funding"
)

type TransferStatus string

const (
	TransferStatusSuccess TransferStatus = "SUCCESS"
	TransferStatusPending TransferStatus = "PENDING"
	TransferStatusFailed  TransferStatus = "FAILED"
)

type CopyTrading string

const (
	CopyTradingNone       CopyTrading = "none"
	CopyTradingBoth       CopyTrading = "both"
	CopyTradingUtaOnly    CopyTrading = "utaOnly"
	CopyTradingNormalOnly CopyTrading = "normalOnly"
)

type UnifiedMarginStatus string

const (
	UnifiedMarginStatus1 UnifiedMarginStatus = "1"
	UnifiedMarginStatus3 UnifiedMarginStatus = "3"
	UnifiedMarginStatus4 UnifiedMarginStatus = "4"
	UnifiedMarginStatus5 UnifiedMarginStatus = "5"
	UnifiedMarginStatus6 UnifiedMarginStatus = "6"
)

type ExtraFeesSubFeeType string

const (
	ExtraFeesSubFeeTypeUnknown           ExtraFeesSubFeeType = "UNKNOWN"
	ExtraFeesSubFeeTypeTaxPnn            ExtraFeesSubFeeType = "TAX_PNN"
	ExtraFeesSubFeeTypeTaxPph            ExtraFeesSubFeeType = "TAX_PPH"
	ExtraFeesSubFeeTypeCfxFiee           ExtraFeesSubFeeType = "CFX_FIEE"
	ExtraFeesSubFeeTypeAutWithholdingTax ExtraFeesSubFeeType = "AUT_WITHHOLDING_TAX"
	ExtraFeesSubFeeTypeIndGst            ExtraFeesSubFeeType = "IND_GST"
	ExtraFeesSubFeeTypeAreVat            ExtraFeesSubFeeType = "ARE_VAT"
)

type TickDirection string

const (
	TickDirectionPlusTick      TickDirection = "PlusTick"
	TickDirectionZeroPlusTick  TickDirection = "ZeroPlusTick"
	TickDirectionMinusTick     TickDirection = "MinusTick"
	TickDirectionZeroMinusTick TickDirection = "ZeroMinusTick"
)

type DepositStatus string

const (
	DepositStatus0     DepositStatus = "0"
	DepositStatus1     DepositStatus = "1"
	DepositStatus2     DepositStatus = "2"
	DepositStatus3     DepositStatus = "3"
	DepositStatus4     DepositStatus = "4"
	DepositStatus10011 DepositStatus = "10011"
	DepositStatus10012 DepositStatus = "10012"
)

type WithdrawStatus string

const (
	WithdrawStatusSecurityCheck           WithdrawStatus = "SecurityCheck"
	WithdrawStatusPending                 WithdrawStatus = "Pending"
	WithdrawStatusSuccess                 WithdrawStatus = "success"
	WithdrawStatusCancelByUser            WithdrawStatus = "CancelByUser"
	WithdrawStatusReject                  WithdrawStatus = "Reject"
	WithdrawStatusFail                    WithdrawStatus = "Fail"
	WithdrawStatusBlockchainConfirmed     WithdrawStatus = "BlockchainConfirmed"
	WithdrawStatusMoreInformationRequired WithdrawStatus = "MoreInformationRequired"
	WithdrawStatusUnknown                 WithdrawStatus = "Unknown"
)

type OptionPeriod string

const (
	OptionPeriod7   OptionPeriod = "7"
	OptionPeriod14  OptionPeriod = "14"
	OptionPeriod21  OptionPeriod = "21"
	OptionPeriod30  OptionPeriod = "30"
	OptionPeriod60  OptionPeriod = "60"
	OptionPeriod90  OptionPeriod = "90"
	OptionPeriod180 OptionPeriod = "180"
	OptionPeriod270 OptionPeriod = "270"
)

type MarginTrading string

const (
	MarginTradingNone           MarginTrading = "none"
	MarginTradingBoth           MarginTrading = "both"
	MarginTradingUtaOnly        MarginTrading = "utaOnly"
	MarginTradingNormalSpotOnly MarginTrading = "normalSpotOnly"
)

type ExtraFeesFeeType string

const (
	ExtraFeesFeeTypeUnknown ExtraFeesFeeType = "UNKNOWN"
	ExtraFeesFeeTypeTax     ExtraFeesFeeType = "TAX"
	ExtraFeesFeeTypeCfx     ExtraFeesFeeType = "CFX"
	ExtraFeesFeeTypeWht     ExtraFeesFeeType = "WHT"
	ExtraFeesFeeTypeGst     ExtraFeesFeeType = "GST"
	ExtraFeesFeeTypeVat     ExtraFeesFeeType = "VAT"
)

type Product string

const (
	Product1 Product = "1"
	Product2 Product = "2"
	Product3 Product = "3"
	Product4 Product = "4"
)

type Msg string

const (
	MsgApiLimitUpdatedSuccessfully                 Msg = "API limit updated successfully"
	MsgRequestedLimitExceedsMaximumAllowedPerUser  Msg = "Requested limit exceeds maximum allowed per user"
	MsgNoPermissionToOperateTheseUiDs              Msg = "No permission to operate these UIDs"
	MsgApiCapConfigurationNotFound                 Msg = "API cap configuration not found"
	MsgApiCapConfigurationNotFoundForBizType       Msg = "API cap configuration not found for bizType"
	MsgRequestedLimitWouldExceedInstitutionalQuota Msg = "Requested limit would exceed institutional quota"
)

type StopOrderType string

const (
	StopOrderTypeTakeProfit             StopOrderType = "TakeProfit"
	StopOrderTypeStopLoss               StopOrderType = "StopLoss"
	StopOrderTypeTrailingStop           StopOrderType = "TrailingStop"
	StopOrderTypeStop                   StopOrderType = "Stop"
	StopOrderTypePartialTakeProfit      StopOrderType = "PartialTakeProfit"
	StopOrderTypePartialStopLoss        StopOrderType = "PartialStopLoss"
	StopOrderTypeTpslOrder              StopOrderType = "tpslOrder"
	StopOrderTypeOcoOrder               StopOrderType = "OcoOrder"
	StopOrderTypeMmRateClose            StopOrderType = "MmRateClose"
	StopOrderTypeBidirectionalTpslOrder StopOrderType = "BidirectionalTpslOrder"
)

type CreateType string

const (
	CreateTypeCreateByUser                              CreateType = "CreateByUser"
	CreateTypeCreateByFutureSpread                      CreateType = "CreateByFutureSpread"
	CreateTypeCreateByAdminClosing                      CreateType = "CreateByAdminClosing"
	CreateTypeCreateBySettle                            CreateType = "CreateBySettle"
	CreateTypeCreateByStopOrder                         CreateType = "CreateByStopOrder"
	CreateTypeCreateByTakeProfit                        CreateType = "CreateByTakeProfit"
	CreateTypeCreateByPartialTakeProfit                 CreateType = "CreateByPartialTakeProfit"
	CreateTypeCreateByStopLoss                          CreateType = "CreateByStopLoss"
	CreateTypeCreateByPartialStopLoss                   CreateType = "CreateByPartialStopLoss"
	CreateTypeCreateByTrailingStop                      CreateType = "CreateByTrailingStop"
	CreateTypeCreateByTrailingProfit                    CreateType = "CreateByTrailingProfit"
	CreateTypeCreateByLiq                               CreateType = "CreateByLiq"
	CreateTypeCreateByTakeOverPassThrough               CreateType = "CreateByTakeOver_PassThrough"
	CreateTypeCreateByAdlPassThrough                    CreateType = "CreateByAdl_PassThrough"
	CreateTypeCreateByBlockPassThrough                  CreateType = "CreateByBlock_PassThrough"
	CreateTypeCreateByBlockTradeMovePositionPassThrough CreateType = "CreateByBlockTradeMovePosition_PassThrough"
	CreateTypeCreateByClosing                           CreateType = "CreateByClosing"
	CreateTypeCreateByFgridBot                          CreateType = "CreateByFGridBot"
	CreateTypeCloseByFgridBot                           CreateType = "CloseByFGridBot"
	CreateTypeCreateByTwap                              CreateType = "CreateByTWAP"
	CreateTypeCreateByTvSignal                          CreateType = "CreateByTVSignal"
	CreateTypeCreateByMmRateClose                       CreateType = "CreateByMmRateClose"
	CreateTypeCreateByMartingaleBot                     CreateType = "CreateByMartingaleBot"
	CreateTypeCloseByMartingaleBot                      CreateType = "CloseByMartingaleBot"
	CreateTypeCreateByIceBerg                           CreateType = "CreateByIceBerg"
	CreateTypeCreateByArbitrage                         CreateType = "CreateByArbitrage"
	CreateTypeCreateByDdh                               CreateType = "CreateByDdh"
	CreateTypeCreateByBboOrder                          CreateType = "CreateByBboOrder"
)

type DataRecordingPeriod string

const (
	DataRecordingPeriod5Min  DataRecordingPeriod = "5min"
	DataRecordingPeriod15Min DataRecordingPeriod = "15min"
	DataRecordingPeriod30Min DataRecordingPeriod = "30min"
	DataRecordingPeriod1H    DataRecordingPeriod = "1h"
	DataRecordingPeriod4H    DataRecordingPeriod = "4h"
	DataRecordingPeriod4D    DataRecordingPeriod = "4d"
)

type Status string

const (
	StatusPreLaunch  Status = "PreLaunch"
	StatusTrading    Status = "Trading"
	StatusDelivering Status = "Delivering"
	StatusClosed     Status = "Closed"
)

type TypeContractTranslog string

const (
	TypeContractTranslogTransferIn     TypeContractTranslog = "TRANSFER_IN"
	TypeContractTranslogTransferOut    TypeContractTranslog = "TRANSFER_OUT"
	TypeContractTranslogTrade          TypeContractTranslog = "TRADE"
	TypeContractTranslogSettlement     TypeContractTranslog = "SETTLEMENT"
	TypeContractTranslogDelivery       TypeContractTranslog = "DELIVERY"
	TypeContractTranslogLiquidation    TypeContractTranslog = "LIQUIDATION"
	TypeContractTranslogAdl            TypeContractTranslog = "ADL"
	TypeContractTranslogAirdrop        TypeContractTranslog = "AIRDROP"
	TypeContractTranslogBonus          TypeContractTranslog = "BONUS"
	TypeContractTranslogBonusRecollect TypeContractTranslog = "BONUS_RECOLLECT"
	TypeContractTranslogFeeRefund      TypeContractTranslog = "FEE_REFUND"
	TypeContractTranslogCurrencyBuy    TypeContractTranslog = "CURRENCY_BUY"
	TypeContractTranslogCurrencySell   TypeContractTranslog = "CURRENCY_SELL"
	TypeContractTranslogAutoDeduction  TypeContractTranslog = "AUTO_DEDUCTION"
	TypeContractTranslogOthers         TypeContractTranslog = "Others"
)

type VipLevel string

const ()

type SmpType string

const (
	SmpTypeNone        SmpType = "None"
	SmpTypeCancelMaker SmpType = "CancelMaker"
	SmpTypeCancelTaker SmpType = "CancelTaker"
	SmpTypeCancelBoth  SmpType = "CancelBoth"
)

type MaintainType string

const (
	MaintainType1 MaintainType = "1"
	MaintainType2 MaintainType = "2"
	MaintainType3 MaintainType = "3"
)

type RejectReason string

const (
	RejectReasonEcNoError                      RejectReason = "EC_NoError"
	RejectReasonEcOthers                       RejectReason = "EC_Others"
	RejectReasonEcUnknownMessageType           RejectReason = "EC_UnknownMessageType"
	RejectReasonEcMissingClOrdId               RejectReason = "EC_MissingClOrdID"
	RejectReasonEcMissingOrigClOrdId           RejectReason = "EC_MissingOrigClOrdID"
	RejectReasonEcClOrdIdOrigClOrdIdAreTheSame RejectReason = "EC_ClOrdIDOrigClOrdIDAreTheSame"
	RejectReasonEcDuplicatedClOrdId            RejectReason = "EC_DuplicatedClOrdID"
	RejectReasonEcOrigClOrdIdDoesNotExist      RejectReason = "EC_OrigClOrdIDDoesNotExist"
	RejectReasonEcTooLateToCancel              RejectReason = "EC_TooLateToCancel"
	RejectReasonEcUnknownOrderType             RejectReason = "EC_UnknownOrderType"
	RejectReasonEcUnknownSide                  RejectReason = "EC_UnknownSide"
	RejectReasonEcUnknownTimeInForce           RejectReason = "EC_UnknownTimeInForce"
	RejectReasonEcWronglyRouted                RejectReason = "EC_WronglyRouted"
	RejectReasonEcMarketOrderPriceIsNotZero    RejectReason = "EC_MarketOrderPriceIsNotZero"
	RejectReasonEcLimitOrderInvalidPrice       RejectReason = "EC_LimitOrderInvalidPrice"
	RejectReasonEcNoEnoughQtyToFill            RejectReason = "EC_NoEnoughQtyToFill"
	RejectReasonEcNoImmediateQtyToFill         RejectReason = "EC_NoImmediateQtyToFill"
	RejectReasonEcPerCancelRequest             RejectReason = "EC_PerCancelRequest"
	RejectReasonEcMarketOrderCannotBePostOnly  RejectReason = "EC_MarketOrderCannotBePostOnly"
	RejectReasonEcPostOnlyWillTakeLiquidity    RejectReason = "EC_PostOnlyWillTakeLiquidity"
	RejectReasonEcCancelReplaceOrder           RejectReason = "EC_CancelReplaceOrder"
	RejectReasonEcInvalidSymbolStatus          RejectReason = "EC_InvalidSymbolStatus"
	RejectReasonEcCancelForNoFullFill          RejectReason = "EC_CancelForNoFullFill"
	RejectReasonEcBySelfMatch                  RejectReason = "EC_BySelfMatch"
	RejectReasonEcInCallAuctionStatus          RejectReason = "EC_InCallAuctionStatus"
	RejectReasonEcQtyCannotBeZero              RejectReason = "EC_QtyCannotBeZero"
	RejectReasonEcMarketOrderNoSupportTif      RejectReason = "EC_MarketOrderNoSupportTIF"
	RejectReasonEcReachMaxTradeNum             RejectReason = "EC_ReachMaxTradeNum"
	RejectReasonEcInvalidPriceScale            RejectReason = "EC_InvalidPriceScale"
	RejectReasonEcBitIndexInvalid              RejectReason = "EC_BitIndexInvalid"
	RejectReasonEcStopBySelfMatch              RejectReason = "EC_StopBySelfMatch"
	RejectReasonEcInvalidSmpType               RejectReason = "EC_InvalidSmpType"
	RejectReasonEcCancelByMmp                  RejectReason = "EC_CancelByMMP"
	RejectReasonEcInvalidUserType              RejectReason = "EC_InvalidUserType"
	RejectReasonEcInvalidMirrorOid             RejectReason = "EC_InvalidMirrorOid"
	RejectReasonEcInvalidMirrorUid             RejectReason = "EC_InvalidMirrorUid"
	RejectReasonEcEcInvalidQty                 RejectReason = "EC_EcInvalidQty"
	RejectReasonEcInvalidAmount                RejectReason = "EC_InvalidAmount"
	RejectReasonEcLoadOrderCancel              RejectReason = "EC_LoadOrderCancel"
	RejectReasonEcMarketQuoteNoSuppSell        RejectReason = "EC_MarketQuoteNoSuppSell"
	RejectReasonEcDisorderOrderId              RejectReason = "EC_DisorderOrderID"
	RejectReasonEcInvalidBaseValue             RejectReason = "EC_InvalidBaseValue"
	RejectReasonEcLoadOrderCanMatch            RejectReason = "EC_LoadOrderCanMatch"
	RejectReasonEcSecurityStatusFail           RejectReason = "EC_SecurityStatusFail"
	RejectReasonEcReachRiskPriceLimit          RejectReason = "EC_ReachRiskPriceLimit"
	RejectReasonEcOrderNotExist                RejectReason = "EC_OrderNotExist"
	RejectReasonEcCancelByOrderValueZero       RejectReason = "EC_CancelByOrderValueZero"
	RejectReasonEcCancelByMatchValueZero       RejectReason = "EC_CancelByMatchValueZero"
	RejectReasonEcReachMarketPriceLimit        RejectReason = "EC_ReachMarketPriceLimit"
)

type ContractType string

const (
	ContractTypeInversePerpetual ContractType = "InversePerpetual"
	ContractTypeLinearPerpetual  ContractType = "LinearPerpetual"
	ContractTypeLinearFutures    ContractType = "LinearFutures"
	ContractTypeInverseFutures   ContractType = "InverseFutures"
)

type SymbolType string

const (
	SymbolTypeInnovation SymbolType = "innovation"
	SymbolTypeAdventure  SymbolType = "adventure"
	SymbolTypeXstocks    SymbolType = "xstocks"
)

type ServiceTypes string

const (
	ServiceTypes1 ServiceTypes = "1"
	ServiceTypes2 ServiceTypes = "2"
	ServiceTypes3 ServiceTypes = "3"
	ServiceTypes4 ServiceTypes = "4"
	ServiceTypes5 ServiceTypes = "5"
)

type Env string

const (
	Env1 Env = "1"
	Env2 Env = "2"
)

type Locale string

const (
	LocaleDeDe  Locale = "de-DE"
	LocaleEnUs  Locale = "en-US"
	LocaleEsAr  Locale = "es-AR"
	LocaleEsEs  Locale = "es-ES"
	LocaleEsMx  Locale = "es-MX"
	LocaleFrFr  Locale = "fr-FR"
	LocaleKkKz  Locale = "kk-KZ"
	LocaleIdId  Locale = "id-ID"
	LocaleUkUa  Locale = "uk-UA"
	LocaleJaJp  Locale = "ja-JP"
	LocaleRuRu  Locale = "ru-RU"
	LocaleThTh  Locale = "th-TH"
	LocalePtBr  Locale = "pt-BR"
	LocaleTrTr  Locale = "tr-TR"
	LocaleViVn  Locale = "vi-VN"
	LocaleZhTw  Locale = "zh-TW"
	LocaleArSa  Locale = "ar-SA"
	LocaleHiIn  Locale = "hi-IN"
	LocaleFilPh Locale = "fil-PH"
)

type AnnouncementTag string

const (
	AnnouncementTagSpot                      AnnouncementTag = "Spot"
	AnnouncementTagDerivatives               AnnouncementTag = "Derivatives"
	AnnouncementTagSpotListings              AnnouncementTag = "Spot Listings"
	AnnouncementTagBtc                       AnnouncementTag = "BTC"
	AnnouncementTagEth                       AnnouncementTag = "ETH"
	AnnouncementTagTradingBots               AnnouncementTag = "Trading Bots"
	AnnouncementTagUsdc                      AnnouncementTag = "USDC"
	AnnouncementTagLeveragedTokens           AnnouncementTag = "Leveraged Tokens"
	AnnouncementTagUsdt                      AnnouncementTag = "USDT"
	AnnouncementTagMarginTrading             AnnouncementTag = "Margin Trading"
	AnnouncementTagPartnerships              AnnouncementTag = "Partnerships"
	AnnouncementTagLaunchpad                 AnnouncementTag = "Launchpad"
	AnnouncementTagUpgrades                  AnnouncementTag = "Upgrades"
	AnnouncementTagByVotes                   AnnouncementTag = "ByVotes"
	AnnouncementTagDelistings                AnnouncementTag = "Delistings"
	AnnouncementTagVip                       AnnouncementTag = "VIP"
	AnnouncementTagFutures                   AnnouncementTag = "Futures"
	AnnouncementTagInstitutions              AnnouncementTag = "Institutions"
	AnnouncementTagOptions                   AnnouncementTag = "Options"
	AnnouncementTagWeb3                      AnnouncementTag = "WEB3"
	AnnouncementTagCopyTrading               AnnouncementTag = "Copy Trading"
	AnnouncementTagEarn                      AnnouncementTag = "Earn"
	AnnouncementTagBybitSavings              AnnouncementTag = "Bybit Savings"
	AnnouncementTagDualAsset                 AnnouncementTag = "Dual Asset"
	AnnouncementTagLiquidityMining           AnnouncementTag = "Liquidity Mining"
	AnnouncementTagSharkFin                  AnnouncementTag = "Shark Fin"
	AnnouncementTagLaunchpool                AnnouncementTag = "Launchpool"
	AnnouncementTagNftGrabPic                AnnouncementTag = "NFT     GrabPic"
	AnnouncementTagBuyCrypto                 AnnouncementTag = "Buy Crypto"
	AnnouncementTagP2PTrading                AnnouncementTag = "P2P Trading"
	AnnouncementTagFiatDeposit               AnnouncementTag = "Fiat Deposit"
	AnnouncementTagCryptoDeposit             AnnouncementTag = "Crypto Deposit"
	AnnouncementTagСпот                      AnnouncementTag = "Спот"
	AnnouncementTagСпотЛістинги              AnnouncementTag = "Спот лістинги"
	AnnouncementTagТорговіБоти               AnnouncementTag = "Торгові боти"
	AnnouncementTagТокениЗКредитнимПлечем    AnnouncementTag = "Токени з кредитним плечем"
	AnnouncementTagМаржинальнаТоргівля       AnnouncementTag = "Маржинальна торгівля"
	AnnouncementTagПартнерство               AnnouncementTag = "Партнерство"
	AnnouncementTagОновлення                 AnnouncementTag = "Оновлення"
	AnnouncementTagДелістинги                AnnouncementTag = "Делістинги"
	AnnouncementTagФЮчерси                   AnnouncementTag = "Ф'ючерси"
	AnnouncementTagОпціони                   AnnouncementTag = "Опціони"
	AnnouncementTagКопітрейдинг              AnnouncementTag = "Копітрейдинг"
	AnnouncementTagBybitНакопичення          AnnouncementTag = "Bybit Накопичення"
	AnnouncementTagБівалютніІнвестиції       AnnouncementTag = "Бівалютні інвестиції"
	AnnouncementTagМайнінгЛіквідності        AnnouncementTag = "Майнінг ліквідності"
	AnnouncementTagКупівляКриптовалюти       AnnouncementTag = "Купівля криптовалюти"
	AnnouncementTagP2PТоргівля               AnnouncementTag = "P2P торгівля"
	AnnouncementTagФіатніДепозити            AnnouncementTag = "Фіатні депозити"
	AnnouncementTagКриптодепозити            AnnouncementTag = "Криптодепозити"
	AnnouncementTagКопитрейдинг              AnnouncementTag = "Копитрейдинг"
	AnnouncementTagТорговыеБоты              AnnouncementTag = "Торговые боты"
	AnnouncementTagДеривативы                AnnouncementTag = "Деривативы"
	AnnouncementTagP2P                       AnnouncementTag = "P2P"
	AnnouncementTagСпотЛистинги              AnnouncementTag = "Спот листинги"
	AnnouncementTagДеривативи                AnnouncementTag = "Деривативи"
	AnnouncementTagMt4                       AnnouncementTag = "MT4"
	AnnouncementTagLuckyDraw                 AnnouncementTag = "Lucky Draw"
	AnnouncementTagUnifiedTradingAccount     AnnouncementTag = "Unified Trading Account"
	AnnouncementTagЄдинийТорговийАкаунт      AnnouncementTag = "Єдиний торговий акаунт"
	AnnouncementTagЕдиныйТорговыйАккаунт     AnnouncementTag = "Единый торговый аккаунт"
	AnnouncementTagИнституциональныйТрейдинг AnnouncementTag = "Институциональный трейдинг"
	AnnouncementTagІнституціональнийТрейдинг AnnouncementTag = "Інституціональний трейдинг"
	AnnouncementTagДелистинг                 AnnouncementTag = "Делистинг"
)

type TimeInForce string

const (
	TimeInForceGtc TimeInForce = "GTC"
	TimeInForceIoc TimeInForce = "IOC"
	TimeInForceFok TimeInForce = "FOK"
)

type PositionStatus string

const (
	PositionStatusNormal PositionStatus = "Normal"
	PositionStatusLiq    PositionStatus = "Liq"
	PositionStatusAdl    PositionStatus = "Adl"
)

type AccountType string

const (
	AccountTypeUnified AccountType = "UNIFIED"
	AccountTypeFund    AccountType = "FUND"
)

type TypeUtaTranslog string

const (
	TypeUtaTranslogTransferIn                            TypeUtaTranslog = "TRANSFER_IN"
	TypeUtaTranslogTransferOut                           TypeUtaTranslog = "TRANSFER_OUT"
	TypeUtaTranslogTrade                                 TypeUtaTranslog = "TRADE"
	TypeUtaTranslogSettlement                            TypeUtaTranslog = "SETTLEMENT"
	TypeUtaTranslogDelivery                              TypeUtaTranslog = "DELIVERY"
	TypeUtaTranslogLiquidation                           TypeUtaTranslog = "LIQUIDATION"
	TypeUtaTranslogAdl                                   TypeUtaTranslog = "ADL"
	TypeUtaTranslogAirdrop                               TypeUtaTranslog = "AIRDROP"
	TypeUtaTranslogBonus                                 TypeUtaTranslog = "BONUS"
	TypeUtaTranslogBonusRecollect                        TypeUtaTranslog = "BONUS_RECOLLECT"
	TypeUtaTranslogFeeRefund                             TypeUtaTranslog = "FEE_REFUND"
	TypeUtaTranslogInterest                              TypeUtaTranslog = "INTEREST"
	TypeUtaTranslogCurrencyBuy                           TypeUtaTranslog = "CURRENCY_BUY"
	TypeUtaTranslogCurrencySell                          TypeUtaTranslog = "CURRENCY_SELL"
	TypeUtaTranslogBorrowedAmountInsLoan                 TypeUtaTranslog = "BORROWED_AMOUNT_INS_LOAN"
	TypeUtaTranslogPrincipleRepaymentInsLoan             TypeUtaTranslog = "PRINCIPLE_REPAYMENT_INS_LOAN"
	TypeUtaTranslogInterestRepaymentInsLoan              TypeUtaTranslog = "INTEREST_REPAYMENT_INS_LOAN"
	TypeUtaTranslogAutoSoldCollateralInsLoan             TypeUtaTranslog = "AUTO_SOLD_COLLATERAL_INS_LOAN"
	TypeUtaTranslogAutoBuyLiabilityInsLoan               TypeUtaTranslog = "AUTO_BUY_LIABILITY_INS_LOAN"
	TypeUtaTranslogAutoPrincipleRepaymentInsLoan         TypeUtaTranslog = "AUTO_PRINCIPLE_REPAYMENT_INS_LOAN"
	TypeUtaTranslogAutoInterestRepaymentInsLoan          TypeUtaTranslog = "AUTO_INTEREST_REPAYMENT_INS_LOAN"
	TypeUtaTranslogTransferInInsLoan                     TypeUtaTranslog = "TRANSFER_IN_INS_LOAN"
	TypeUtaTranslogTransferOutInsLoan                    TypeUtaTranslog = "TRANSFER_OUT_INS_LOAN"
	TypeUtaTranslogSpotRepaymentSell                     TypeUtaTranslog = "SPOT_REPAYMENT_SELL"
	TypeUtaTranslogSpotRepaymentBuy                      TypeUtaTranslog = "SPOT_REPAYMENT_BUY"
	TypeUtaTranslogTokensSubscription                    TypeUtaTranslog = "TOKENS_SUBSCRIPTION"
	TypeUtaTranslogTokensRedemption                      TypeUtaTranslog = "TOKENS_REDEMPTION"
	TypeUtaTranslogAutoDeduction                         TypeUtaTranslog = "AUTO_DEDUCTION"
	TypeUtaTranslogFlexibleStakingSubscription           TypeUtaTranslog = "FLEXIBLE_STAKING_SUBSCRIPTION"
	TypeUtaTranslogFlexibleStakingRedemption             TypeUtaTranslog = "FLEXIBLE_STAKING_REDEMPTION"
	TypeUtaTranslogFixedStakingSubscription              TypeUtaTranslog = "FIXED_STAKING_SUBSCRIPTION"
	TypeUtaTranslogFlexibleStakingRefund                 TypeUtaTranslog = "FLEXIBLE_STAKING_REFUND"
	TypeUtaTranslogFixedStakingRefund                    TypeUtaTranslog = "FIXED_STAKING_REFUND"
	TypeUtaTranslogPremarketTransferOut                  TypeUtaTranslog = "PREMARKET_TRANSFER_OUT"
	TypeUtaTranslogPremarketDeliverySellNewCoin          TypeUtaTranslog = "PREMARKET_DELIVERY_SELL_NEW_COIN"
	TypeUtaTranslogPremarketDeliveryBuyNewCoin           TypeUtaTranslog = "PREMARKET_DELIVERY_BUY_NEW_COIN"
	TypeUtaTranslogPremarketDeliveryPledgePaySeller      TypeUtaTranslog = "PREMARKET_DELIVERY_PLEDGE_PAY_SELLER"
	TypeUtaTranslogPremarketDeliveryPledgeBack           TypeUtaTranslog = "PREMARKET_DELIVERY_PLEDGE_BACK"
	TypeUtaTranslogPremarketRollbackPledgeBack           TypeUtaTranslog = "PREMARKET_ROLLBACK_PLEDGE_BACK"
	TypeUtaTranslogPremarketRollbackPledgePenaltyToBuyer TypeUtaTranslog = "PREMARKET_ROLLBACK_PLEDGE_PENALTY_TO_BUYER"
	TypeUtaTranslogCustodyNetworkFee                     TypeUtaTranslog = "CUSTODY_NETWORK_FEE"
	TypeUtaTranslogCustodySettleFee                      TypeUtaTranslog = "CUSTODY_SETTLE_FEE"
	TypeUtaTranslogCustodyLock                           TypeUtaTranslog = "CUSTODY_LOCK"
	TypeUtaTranslogCustodyUnlock                         TypeUtaTranslog = "CUSTODY_UNLOCK"
	TypeUtaTranslogCustodyUnlockRefund                   TypeUtaTranslog = "CUSTODY_UNLOCK_REFUND"
	TypeUtaTranslogLoansBorrowFunds                      TypeUtaTranslog = "LOANS_BORROW_FUNDS"
	TypeUtaTranslogLoansPledgeAsset                      TypeUtaTranslog = "LOANS_PLEDGE_ASSET"
	TypeUtaTranslogBonusTransferIn                       TypeUtaTranslog = "BONUS_TRANSFER_IN"
	TypeUtaTranslogBonusTransferOut                      TypeUtaTranslog = "BONUS_TRANSFER_OUT"
	TypeUtaTranslogPefTransferIn                         TypeUtaTranslog = "PEF_TRANSFER_IN"
	TypeUtaTranslogPefTransferOut                        TypeUtaTranslog = "PEF_TRANSFER_OUT"
	TypeUtaTranslogPefProfitShare                        TypeUtaTranslog = "PEF_PROFIT_SHARE"
	TypeUtaTranslogOnchainearnSubscription               TypeUtaTranslog = "ONCHAINEARN_SUBSCRIPTION"
	TypeUtaTranslogOnchainearnRedemption                 TypeUtaTranslog = "ONCHAINEARN_REDEMPTION"
	TypeUtaTranslogOnchainearnRefund                     TypeUtaTranslog = "ONCHAINEARN_REFUND"
	TypeUtaTranslogStructureProductSubscription          TypeUtaTranslog = "STRUCTURE_PRODUCT_SUBSCRIPTION"
	TypeUtaTranslogStructureProductRefund                TypeUtaTranslog = "STRUCTURE_PRODUCT_REFUND"
	TypeUtaTranslogClassicWealthManagementSubscription   TypeUtaTranslog = "CLASSIC_WEALTH_MANAGEMENT_SUBSCRIPTION"
	TypeUtaTranslogPremimumWealthManagementSubscription  TypeUtaTranslog = "PREMIMUM_WEALTH_MANAGEMENT_SUBSCRIPTION"
	TypeUtaTranslogPremimumWealthManagementRefund        TypeUtaTranslog = "PREMIMUM_WEALTH_MANAGEMENT_REFUND"
	TypeUtaTranslogLiquidityMiningSubscription           TypeUtaTranslog = "LIQUIDITY_MINING_SUBSCRIPTION"
	TypeUtaTranslogLiquidityMiningRefund                 TypeUtaTranslog = "LIQUIDITY_MINING_REFUND"
	TypeUtaTranslogPwmSubscription                       TypeUtaTranslog = "PWM_SUBSCRIPTION"
	TypeUtaTranslogPwmRefund                             TypeUtaTranslog = "PWM_REFUND"
	TypeUtaTranslogDefiInvestmentSubscription            TypeUtaTranslog = "DEFI_INVESTMENT_SUBSCRIPTION"
	TypeUtaTranslogDefiInvestmentRefund                  TypeUtaTranslog = "DEFI_INVESTMENT_REFUND"
	TypeUtaTranslogDefiInvestmentRedemption              TypeUtaTranslog = "DEFI_INVESTMENT_REDEMPTION"
	TypeUtaTranslogInstitutionLoanIn                     TypeUtaTranslog = "INSTITUTION_LOAN_IN"
	TypeUtaTranslogInstitutionPaybackPrincipalOut        TypeUtaTranslog = "INSTITUTION_PAYBACK_PRINCIPAL_OUT"
	TypeUtaTranslogInstitutionPaybackInterestOut         TypeUtaTranslog = "INSTITUTION_PAYBACK_INTEREST_OUT"
	TypeUtaTranslogInstitutionExchangeSell               TypeUtaTranslog = "INSTITUTION_EXCHANGE_SELL"
	TypeUtaTranslogInstitutionExchangeBuy                TypeUtaTranslog = "INSTITUTION_EXCHANGE_BUY"
	TypeUtaTranslogInstitutionLiqPrincipalOut            TypeUtaTranslog = "INSTITUTION_LIQ_PRINCIPAL_OUT"
	TypeUtaTranslogInstitutionLiqInterestOut             TypeUtaTranslog = "INSTITUTION_LIQ_INTEREST_OUT"
	TypeUtaTranslogInstitutionLoanTransferIn             TypeUtaTranslog = "INSTITUTION_LOAN_TRANSFER_IN"
	TypeUtaTranslogInstitutionLoanTransferOut            TypeUtaTranslog = "INSTITUTION_LOAN_TRANSFER_OUT"
	TypeUtaTranslogInstitutionLoanWithoutWithdraw        TypeUtaTranslog = "INSTITUTION_LOAN_WITHOUT_WITHDRAW"
	TypeUtaTranslogInstitutionLoanReserveIn              TypeUtaTranslog = "INSTITUTION_LOAN_RESERVE_IN"
	TypeUtaTranslogInstitutionLoanReserveOut             TypeUtaTranslog = "INSTITUTION_LOAN_RESERVE_OUT"
	TypeUtaTranslogSpreadFeeOut                          TypeUtaTranslog = "SPREAD_FEE_OUT"
	TypeUtaTranslogPlatformTokenMntLiqrecalledmmnt       TypeUtaTranslog = "PLATFORM_TOKEN_MNT_LIQRECALLEDMMNT"
	TypeUtaTranslogPlatformTokenMntLiqreturnedmnt        TypeUtaTranslog = "PLATFORM_TOKEN_MNT_LIQRETURNEDMNT"
	TypeUtaTranslogBorrow                                TypeUtaTranslog = "BORROW"
	TypeUtaTranslogRepay                                 TypeUtaTranslog = "REPAY"
	TypeUtaTranslogConvert                               TypeUtaTranslog = "CONVERT"
	TypeUtaTranslogBrokerAbaccountFee                    TypeUtaTranslog = "BROKER_ABACCOUNT_FEE"
	TypeUtaTranslogEarningRedemptionSell                 TypeUtaTranslog = "EARNING_REDEMPTION_SELL"
	TypeUtaTranslogEarningRedemptionBuy                  TypeUtaTranslog = "EARNING_REDEMPTION_BUY"
	TypeUtaTranslogDbsCashOut                            TypeUtaTranslog = "DBS_CASH_OUT"
	TypeUtaTranslogDbsCashIn                             TypeUtaTranslog = "DBS_CASH_IN"
	TypeUtaTranslogDbsCashOutTr                          TypeUtaTranslog = "DBS_CASH_OUT_TR"
	TypeUtaTranslogDbsCashInTr                           TypeUtaTranslog = "DBS_CASH_IN_TR"
	TypeUtaTranslogCustodyCashRecoverTr                  TypeUtaTranslog = "CUSTODY_CASH_RECOVER_TR"
	TypeUtaTranslogAlphaSmallTokenRefund                 TypeUtaTranslog = "ALPHA_SMALL_TOKEN_REFUND"
	TypeUtaTranslogTwapBudgetAirdrop                     TypeUtaTranslog = "TWAP_BUDGET_AIRDROP"
	TypeUtaTranslogTwapBudgetRecall                      TypeUtaTranslog = "TWAP_BUDGET_RECALL"
	TypeUtaTranslogFloatingToFixedBorrow                 TypeUtaTranslog = "FLOATING_TO_FIXED_BORROW"
	TypeUtaTranslogFloatingToFixedRepay                  TypeUtaTranslog = "FLOATING_TO_FIXED_REPAY"
	TypeUtaTranslogIdnConvertIn                          TypeUtaTranslog = "IDN_CONVERT_IN"
	TypeUtaTranslogIdnConvertOut                         TypeUtaTranslog = "IDN_CONVERT_OUT"
)

type ConvertAccountType string

const (
	ConvertAccountTypeEbConvertUta     ConvertAccountType = "eb_convert_uta"
	ConvertAccountTypeEbConvertFunding ConvertAccountType = "eb_convert_funding"
)

type Symbol string

const (
	SymbolBtcusdt              Symbol = "BTCUSDT"
	SymbolEthusdt              Symbol = "ETHUSDT"
	SymbolBtcusdt21Feb25       Symbol = "BTCUSDT-21FEB25"
	SymbolEthusdt14Feb25       Symbol = "ETHUSDT-14FEB25"
	SymbolBtcperp              Symbol = "BTCPERP"
	SymbolEthperp              Symbol = "ETHPERP"
	SymbolBtc24Mar23           Symbol = "BTC-24MAR23"
	SymbolBtcusd               Symbol = "BTCUSD"
	SymbolEthusd               Symbol = "ETHUSD"
	SymbolBtcusdh23            Symbol = "BTCUSDH23"
	SymbolBtcusdm23            Symbol = "BTCUSDM23"
	SymbolBtcusdu23            Symbol = "BTCUSDU23"
	SymbolBtcusdz23            Symbol = "BTCUSDZ23"
	SymbolEthusdc              Symbol = "ETHUSDC"
	SymbolBtc13Feb2589000PUsdt Symbol = "BTC-13FEB25-89000-P-USDT"
	SymbolEth28Feb252800C      Symbol = "ETH-28FEB25-2800-C"
)

type CancelType string

const (
	CancelTypeCancelByUser                       CancelType = "CancelByUser"
	CancelTypeCancelByReduceOnly                 CancelType = "CancelByReduceOnly"
	CancelTypeCancelByPrepareLiq                 CancelType = "CancelByPrepareLiq"
	CancelTypeCancelAllBeforeLiq                 CancelType = "CancelAllBeforeLiq"
	CancelTypeCancelByPrepareAdl                 CancelType = "CancelByPrepareAdl"
	CancelTypeCancelAllBeforeAdl                 CancelType = "CancelAllBeforeAdl"
	CancelTypeCancelByAdmin                      CancelType = "CancelByAdmin"
	CancelTypeCancelBySettle                     CancelType = "CancelBySettle"
	CancelTypeCancelByTpSlTsClear                CancelType = "CancelByTpSlTsClear"
	CancelTypeCancelBySmp                        CancelType = "CancelBySmp"
	CancelTypeCancelByDcp                        CancelType = "CancelByDCP"
	CancelTypeCancelByRebalance                  CancelType = "CancelByRebalance"
	CancelTypeCancelByOcoTpcanceledBySlTriggered CancelType = "CancelByOCOTpCanceledBySlTriggered"
	CancelTypeCancelByOcoSlcanceledByTpTriggered CancelType = "CancelByOCOSlCanceledByTpTriggered"
	CancelTypeCancelByCannotAffordOrderCost      CancelType = "CancelByCannotAffordOrderCost"
	CancelTypeCancelByPmTrialMmOverEquity        CancelType = "CancelByPmTrialMmOverEquity"
	CancelTypeCancelByAccountBlocking            CancelType = "CancelByAccountBlocking"
	CancelTypeCancelByDelivery                   CancelType = "CancelByDelivery"
	CancelTypeCancelByMmpTriggered               CancelType = "CancelByMmpTriggered"
	CancelTypeCancelByCrossSelfMuch              CancelType = "CancelByCrossSelfMuch"
	CancelTypeCancelByCrossReachMaxTradeNum      CancelType = "CancelByCrossReachMaxTradeNum"
)

type AdlRankIndicator string

const (
	AdlRankIndicator0 AdlRankIndicator = "0"
	AdlRankIndicator1 AdlRankIndicator = "1"
	AdlRankIndicator2 AdlRankIndicator = "2"
	AdlRankIndicator3 AdlRankIndicator = "3"
	AdlRankIndicator4 AdlRankIndicator = "4"
	AdlRankIndicator5 AdlRankIndicator = "5"
)

type State string

const (
	StateScheduled State = "scheduled"
	StateOngoing   State = "ongoing"
	StateCompleted State = "completed"
	StateCanceled  State = "canceled"
)
